//! Static catalog of all known access scopes.
//!
//! This is the single source of truth for scope labels, descriptions,
//! and UI metadata. Used by the permission matrix and audit pages.

use contracts::system::access::{ScopeDescriptor, ScopeType};

pub const SCOPE_CATALOG: &[ScopeDescriptor] = &[
    // ========================================================================
    // AGGREGATES — References / Справочники
    // ========================================================================
    ScopeDescriptor {
        scope_id: "a001_connection_1c",
        scope_type: ScopeType::Aggregate,
        label: "Подключения 1С",
        description: "Настройки подключения к системам 1С для синхронизации данных",
        icon: "plug",
        category: "references",
        read_label: "Просмотр подключений",
        all_label: "Создание и редактирование подключений",
    },
    ScopeDescriptor {
        scope_id: "a002_organization",
        scope_type: ScopeType::Aggregate,
        label: "Организации",
        description: "Справочник организаций компании",
        icon: "building-2",
        category: "references",
        read_label: "Просмотр организаций",
        all_label: "Создание и редактирование организаций",
    },
    ScopeDescriptor {
        scope_id: "a003_counterparty",
        scope_type: ScopeType::Aggregate,
        label: "Контрагенты",
        description: "Справочник контрагентов (поставщики, покупатели)",
        icon: "users",
        category: "references",
        read_label: "Просмотр контрагентов",
        all_label: "Создание и редактирование контрагентов",
    },
    ScopeDescriptor {
        scope_id: "a004_nomenclature",
        scope_type: ScopeType::Aggregate,
        label: "Номенклатура",
        description: "Справочник товаров и продуктов",
        icon: "package",
        category: "references",
        read_label: "Просмотр номенклатуры",
        all_label: "Создание и редактирование номенклатуры",
    },
    ScopeDescriptor {
        scope_id: "a005_marketplace",
        scope_type: ScopeType::Aggregate,
        label: "Маркетплейсы",
        description: "Справочник маркетплейсов (WB, Ozon, Яндекс Маркет)",
        icon: "store",
        category: "references",
        read_label: "Просмотр маркетплейсов",
        all_label: "Создание и редактирование маркетплейсов",
    },
    ScopeDescriptor {
        scope_id: "a006_connection_mp",
        scope_type: ScopeType::Aggregate,
        label: "Подключения к маркетплейсам",
        description: "API-токены и настройки подключения к кабинетам маркетплейсов",
        icon: "key",
        category: "references",
        read_label: "Просмотр подключений",
        all_label: "Создание и редактирование подключений",
    },
    ScopeDescriptor {
        scope_id: "a007_marketplace_product",
        scope_type: ScopeType::Aggregate,
        label: "Товары на маркетплейсах",
        description: "Карточки товаров, привязанных к кабинетам маркетплейсов",
        icon: "shopping-bag",
        category: "references",
        read_label: "Просмотр товаров",
        all_label: "Создание и редактирование товаров",
    },
    // ========================================================================
    // AGGREGATES — Marketplace data / Торговые данные
    // ========================================================================
    ScopeDescriptor {
        scope_id: "a008_marketplace_sales",
        scope_type: ScopeType::Aggregate,
        label: "Продажи маркетплейсов",
        description: "Сводные данные о продажах по всем маркетплейсам",
        icon: "trending-up",
        category: "marketplace_data",
        read_label: "Просмотр продаж",
        all_label: "Управление данными продаж",
    },
    ScopeDescriptor {
        scope_id: "a009_ozon_returns",
        scope_type: ScopeType::Aggregate,
        label: "Возвраты Ozon",
        description: "Данные о возвратах товаров на Ozon",
        icon: "rotate-ccw",
        category: "marketplace_data",
        read_label: "Просмотр возвратов",
        all_label: "Управление данными возвратов",
    },
    ScopeDescriptor {
        scope_id: "a010_ozon_fbs_posting",
        scope_type: ScopeType::Aggregate,
        label: "Отправления Ozon FBS",
        description: "Отправления по схеме FBS (Fulfillment by Seller) на Ozon",
        icon: "truck",
        category: "marketplace_data",
        read_label: "Просмотр отправлений",
        all_label: "Управление отправлениями",
    },
    ScopeDescriptor {
        scope_id: "a011_ozon_fbo_posting",
        scope_type: ScopeType::Aggregate,
        label: "Отправления Ozon FBO",
        description: "Отправления по схеме FBO (Fulfillment by Ozon)",
        icon: "warehouse",
        category: "marketplace_data",
        read_label: "Просмотр отправлений",
        all_label: "Управление отправлениями",
    },
    ScopeDescriptor {
        scope_id: "a012_wb_sales",
        scope_type: ScopeType::Aggregate,
        label: "Продажи Wildberries",
        description: "Данные о продажах товаров на Wildberries",
        icon: "trending-up",
        category: "marketplace_data",
        read_label: "Просмотр продаж WB",
        all_label: "Управление данными продаж WB",
    },
    ScopeDescriptor {
        scope_id: "a013_ym_order",
        scope_type: ScopeType::Aggregate,
        label: "Заказы Яндекс Маркет",
        description: "Данные о заказах на Яндекс Маркет",
        icon: "shopping-cart",
        category: "marketplace_data",
        read_label: "Просмотр заказов ЯМ",
        all_label: "Управление заказами ЯМ",
    },
    ScopeDescriptor {
        scope_id: "a014_ozon_transactions",
        scope_type: ScopeType::Aggregate,
        label: "Транзакции Ozon",
        description: "Финансовые транзакции по кабинетам Ozon",
        icon: "receipt",
        category: "marketplace_data",
        read_label: "Просмотр транзакций",
        all_label: "Управление транзакциями",
    },
    ScopeDescriptor {
        scope_id: "a015_wb_orders",
        scope_type: ScopeType::Aggregate,
        label: "Заказы Wildberries",
        description: "Данные о заказах на Wildberries",
        icon: "shopping-cart",
        category: "marketplace_data",
        read_label: "Просмотр заказов WB",
        all_label: "Управление заказами WB",
    },
    ScopeDescriptor {
        scope_id: "a016_ym_returns",
        scope_type: ScopeType::Aggregate,
        label: "Возвраты Яндекс Маркет",
        description: "Данные о возвратах товаров на Яндекс Маркет",
        icon: "rotate-ccw",
        category: "marketplace_data",
        read_label: "Просмотр возвратов ЯМ",
        all_label: "Управление возвратами ЯМ",
    },
    ScopeDescriptor {
        scope_id: "a020_wb_promotion",
        scope_type: ScopeType::Aggregate,
        label: "Акции Wildberries",
        description: "Рекламные акции и скидки на Wildberries",
        icon: "percent",
        category: "marketplace_data",
        read_label: "Просмотр акций WB",
        all_label: "Управление акциями WB",
    },
    ScopeDescriptor {
        scope_id: "a026_wb_advert_daily",
        scope_type: ScopeType::Aggregate,
        label: "Реклама Wildberries (daily)",
        description: "Ежедневная статистика рекламных кампаний Wildberries",
        icon: "bar-chart-2",
        category: "marketplace_data",
        read_label: "Просмотр рекламной статистики",
        all_label: "Управление рекламными данными",
    },
    ScopeDescriptor {
        scope_id: "a036_wb_sales_funnel_daily",
        scope_type: ScopeType::Aggregate,
        label: "Воронка продаж WB",
        description: "Ежедневная воронка продаж Wildberries в разрезе номенклатуры",
        icon: "filter",
        category: "marketplace_data",
        read_label: "Просмотр воронки продаж WB",
        all_label: "Управление воронкой продаж WB",
    },
    ScopeDescriptor {
        scope_id: "a037_wb_product_snapshot",
        scope_type: ScopeType::Aggregate,
        label: "Данные по товарам WB",
        description: "Ежедневные данные по остаткам и рейтингам товаров Wildberries",
        icon: "package",
        category: "marketplace_data",
        read_label: "Просмотр данных по товарам WB",
        all_label: "Управление данными по товарам WB",
    },
    ScopeDescriptor {
        scope_id: "a040_wb_search_analytics_daily",
        scope_type: ScopeType::Aggregate,
        label: "Поисковая аналитика WB",
        description: "Показы, позиции в выдаче и поисковые запросы товаров Wildberries",
        icon: "search",
        category: "marketplace_data",
        read_label: "Просмотр поисковой аналитики WB",
        all_label: "Управление поисковой аналитикой WB",
    },
    ScopeDescriptor {
        scope_id: "a043_wb_finance_report",
        scope_type: ScopeType::Aggregate,
        label: "Финансовые отчёты WB (новый API)",
        description: "Ежедневные отчёты реализации WB Finance API v1 без проекций",
        icon: "money",
        category: "marketplace_data",
        read_label: "Просмотр новых финансовых отчётов WB",
        all_label: "Управление новыми финансовыми отчётами WB",
    },
    ScopeDescriptor {
        scope_id: "a034_ym_realization",
        scope_type: ScopeType::Aggregate,
        label: "Реализация YM (Отчёт о реализации)",
        description: "Официальный отчёт о реализации Yandex Market, слой ybuh",
        icon: "receipt",
        category: "marketplace_data",
        read_label: "Просмотр реализации YM",
        all_label: "Управление реализацией YM",
    },
    ScopeDescriptor {
        scope_id: "a027_wb_documents",
        scope_type: ScopeType::Aggregate,
        label: "Документы Wildberries",
        description: "Документы поставок и логистики Wildberries",
        icon: "file-text",
        category: "marketplace_data",
        read_label: "Просмотр документов WB",
        all_label: "Управление документами WB",
    },
    ScopeDescriptor {
        scope_id: "a029_wb_supply",
        scope_type: ScopeType::Aggregate,
        label: "Поставки Wildberries",
        description: "Поставки товаров на склады Wildberries",
        icon: "package-check",
        category: "marketplace_data",
        read_label: "Просмотр поставок WB",
        all_label: "Управление поставками WB",
    },
    ScopeDescriptor {
        scope_id: "a030_wb_advert_campaign",
        scope_type: ScopeType::Aggregate,
        label: "Кампании рекламы Wildberries",
        description: "Справочник рекламных кампаний Wildberries и их свойств",
        icon: "megaphone",
        category: "marketplace_data",
        read_label: "Просмотр рекламных кампаний WB",
        all_label: "Управление рекламными кампаниями WB",
    },
    // ========================================================================
    // AGGREGATES — Production / Производство и закупки
    // ========================================================================
    ScopeDescriptor {
        scope_id: "a021_production_output",
        scope_type: ScopeType::Aggregate,
        label: "Выпуск продукции",
        description: "Данные о выпуске продукции на производстве",
        icon: "factory",
        category: "production",
        read_label: "Просмотр выпуска",
        all_label: "Управление данными выпуска",
    },
    ScopeDescriptor {
        scope_id: "a022_kit_variant",
        scope_type: ScopeType::Aggregate,
        label: "Варианты комплектов",
        description: "Конфигурации комплектов и наборов товаров",
        icon: "layers",
        category: "production",
        read_label: "Просмотр комплектов",
        all_label: "Управление комплектами",
    },
    ScopeDescriptor {
        scope_id: "a023_purchase_of_goods",
        scope_type: ScopeType::Aggregate,
        label: "Закупки товаров",
        description: "Данные о закупках товаров у поставщиков",
        icon: "shopping-bag",
        category: "production",
        read_label: "Просмотр закупок",
        all_label: "Управление закупками",
    },
    ScopeDescriptor {
        scope_id: "a028_missing_cost_registry",
        scope_type: ScopeType::Aggregate,
        label: "Реестр незакрытых себестоимостей",
        description: "Позиции без рассчитанной себестоимости",
        icon: "alert-triangle",
        category: "production",
        read_label: "Просмотр реестра",
        all_label: "Управление реестром",
    },
    // ========================================================================
    // AGGREGATES — Analytics / Аналитика
    // ========================================================================
    ScopeDescriptor {
        scope_id: "a024_bi_indicator",
        scope_type: ScopeType::Aggregate,
        label: "BI Индикаторы",
        description: "Индикаторы BI-дашбордов — конфигурации источников данных и отображения",
        icon: "activity",
        category: "analytics",
        read_label: "Просмотр индикаторов",
        all_label: "Создание и редактирование индикаторов",
    },
    ScopeDescriptor {
        scope_id: "a025_bi_dashboard",
        scope_type: ScopeType::Aggregate,
        label: "BI Дашборды",
        description: "Аналитические дашборды с наборами индикаторов и фильтрами",
        icon: "layout-dashboard",
        category: "analytics",
        read_label: "Просмотр дашбордов",
        all_label: "Создание и редактирование дашбордов",
    },
    ScopeDescriptor {
        scope_id: "bi_timeline",
        scope_type: ScopeType::System,
        label: "BI Timeline",
        description: "Проверка динамики BI-индикаторов по дневным рядам и двум периодам",
        icon: "line-chart",
        category: "analytics",
        read_label: "Просмотр BI Timeline",
        all_label: "Просмотр и настройка BI Timeline",
    },
    // ========================================================================
    // AGGREGATES — AI / LLM
    // ========================================================================
    ScopeDescriptor {
        scope_id: "a017_llm_agent",
        scope_type: ScopeType::Aggregate,
        label: "LLM Агенты",
        description: "Конфигурации AI-агентов на базе языковых моделей",
        icon: "bot",
        category: "ai",
        read_label: "Просмотр агентов",
        all_label: "Управление агентами",
    },
    ScopeDescriptor {
        scope_id: "a018_llm_chat",
        scope_type: ScopeType::Aggregate,
        label: "LLM Чаты",
        description: "Сессии чатов с языковыми моделями",
        icon: "message-square",
        category: "ai",
        read_label: "Просмотр чатов",
        all_label: "Создание и управление чатами",
    },
    ScopeDescriptor {
        scope_id: "a019_llm_artifact",
        scope_type: ScopeType::Aggregate,
        label: "LLM Артефакты",
        description: "Артефакты, созданные языковыми моделями",
        icon: "file-code",
        category: "ai",
        read_label: "Просмотр артефактов",
        all_label: "Управление артефактами",
    },
    ScopeDescriptor {
        scope_id: "a038_llm_connection",
        scope_type: ScopeType::Aggregate,
        label: "Подключения LLM",
        description: "Настройки подключений к провайдерам языковых моделей",
        icon: "plug",
        category: "ai",
        read_label: "Просмотр подключений LLM",
        all_label: "Создание и редактирование подключений LLM",
    },
    ScopeDescriptor {
        scope_id: "a039_mail_message",
        scope_type: ScopeType::Aggregate,
        label: "Письма (журнал)",
        description: "Журнал входящих и исходящих писем почтового конвейера LLM-агентов",
        icon: "mail",
        category: "ai",
        read_label: "Просмотр журнала писем",
        all_label: "Управление журналом писем",
    },
    ScopeDescriptor {
        scope_id: "a031_kb_edit",
        scope_type: ScopeType::Aggregate,
        label: "Редактирование базы знаний",
        description:
            "Тикеты администратора базы знаний: предложения, обсуждения и публикация статей",
        icon: "book-open",
        category: "ai",
        read_label: "Просмотр редактирований базы знаний",
        all_label: "Управление редактированиями базы знаний",
    },
    ScopeDescriptor {
        scope_id: "a042_agent_task",
        scope_type: ScopeType::Aggregate,
        label: "Поручения AI-сотрудникам",
        description:
            "Очередь задач, которые агенты передают друг другу: постановка, статус, результат",
        icon: "share-2",
        category: "ai",
        read_label: "Просмотр поручений AI-сотрудникам",
        all_label: "Управление поручениями AI-сотрудникам",
    },
    ScopeDescriptor {
        scope_id: "a032_wb_returns_claims",
        scope_type: ScopeType::Aggregate,
        label: "Заявки на возврат WB",
        description:
            "Заявки покупателей на возврат товара Wildberries (feedbacks-api /api/v1/claims)",
        icon: "rotate-ccw",
        category: "wildberries",
        read_label: "Просмотр заявок на возврат WB",
        all_label: "Управление заявками на возврат WB",
    },
    ScopeDescriptor {
        scope_id: "a033_wb_day_close",
        scope_type: ScopeType::Aggregate,
        label: "Закрытие дня WB",
        description:
            "Документ-снапшот итогов дня WB-кабинета: 10 колонок по заказам, проверка рекламной атрибуции",
        icon: "calendar-check",
        category: "wildberries",
        read_label: "Просмотр закрытий дня WB",
        all_label: "Управление закрытиями дня WB",
    },
    ScopeDescriptor {
        scope_id: "knowledge_base",
        scope_type: ScopeType::System,
        label: "База знаний",
        description: "Просмотр статей базы знаний, словаря тегов, статистики и замечаний; \
                      полный доступ добавляет перечитывание базы с диска",
        icon: "book-open-text",
        category: "ai",
        read_label: "Просмотр базы знаний",
        all_label: "Просмотр и управление базой знаний",
    },
    // ========================================================================
    // PROJECTIONS — Analytics / Аналитика
    // ========================================================================
    ScopeDescriptor {
        scope_id: "p900_mp_sales_register",
        scope_type: ScopeType::Projection,
        label: "Реестр продаж",
        description: "Сводный аналитический реестр всех продаж по маркетплейсам",
        icon: "receipt",
        category: "analytics",
        read_label: "Просмотр реестра продаж и статистики",
        all_label: "Просмотр и служебные операции с реестром",
    },
    ScopeDescriptor {
        scope_id: "p901_nomenclature_barcodes",
        scope_type: ScopeType::Projection,
        label: "Штрихкоды номенклатуры",
        description: "Справочник штрихкодов, привязанных к номенклатуре",
        icon: "scan-barcode",
        category: "references",
        read_label: "Просмотр штрихкодов",
        all_label: "Просмотр штрихкодов",
    },
    ScopeDescriptor {
        scope_id: "p902_ozon_finance_realization",
        scope_type: ScopeType::Projection,
        label: "Финансовая реализация Ozon",
        description: "Данные финансовой реализации по кабинетам Ozon",
        icon: "dollar-sign",
        category: "analytics",
        read_label: "Просмотр финансовых данных Ozon",
        all_label: "Просмотр финансовых данных Ozon",
    },
    ScopeDescriptor {
        scope_id: "p903_wb_finance_report",
        scope_type: ScopeType::Projection,
        label: "Финансовый отчёт Wildberries",
        description: "Отчёты о реализации и комиссиях Wildberries",
        icon: "file-spreadsheet",
        category: "analytics",
        read_label: "Просмотр финансового отчёта WB",
        all_label: "Просмотр и проведение строк отчёта WB",
    },
    ScopeDescriptor {
        scope_id: "p904_sales_data",
        scope_type: ScopeType::Projection,
        label: "Данные продаж",
        description: "Агрегированные данные продаж для аналитики",
        icon: "bar-chart",
        category: "analytics",
        read_label: "Просмотр данных продаж",
        all_label: "Просмотр данных продаж",
    },
    ScopeDescriptor {
        scope_id: "p905_wb_commission_history",
        scope_type: ScopeType::Projection,
        label: "История комиссий Wildberries",
        description: "Исторические данные о ставках комиссий Wildberries",
        icon: "percent",
        category: "analytics",
        read_label: "Просмотр истории комиссий",
        all_label: "Просмотр и редактирование комиссий",
    },
    ScopeDescriptor {
        scope_id: "p906_nomenclature_prices",
        scope_type: ScopeType::Projection,
        label: "Цены номенклатуры",
        description: "История цен на товары по периодам",
        icon: "tag",
        category: "analytics",
        read_label: "Просмотр цен",
        all_label: "Просмотр и импорт цен",
    },
    ScopeDescriptor {
        scope_id: "p907_ym_payment_report",
        scope_type: ScopeType::Projection,
        label: "Отчёт по выплатам Яндекс Маркет",
        description: "Отчёты о выплатах по кабинетам Яндекс Маркет",
        icon: "file-text",
        category: "analytics",
        read_label: "Просмотр отчётов ЯМ",
        all_label: "Просмотр отчётов ЯМ",
    },
    ScopeDescriptor {
        scope_id: "p908_wb_goods_prices",
        scope_type: ScopeType::Projection,
        label: "Цены товаров Wildberries",
        description: "Текущие цены товаров в каталоге Wildberries",
        icon: "tag",
        category: "analytics",
        read_label: "Просмотр цен товаров WB",
        all_label: "Просмотр цен товаров WB",
    },
    ScopeDescriptor {
        scope_id: "p912_nomenclature_costs",
        scope_type: ScopeType::Projection,
        label: "Себестоимость номенклатуры",
        description: "Рассчитанная себестоимость товаров",
        icon: "calculator",
        category: "analytics",
        read_label: "Просмотр себестоимости",
        all_label: "Просмотр себестоимости",
    },
    // ========================================================================
    // USECASES — Imports / Импорт данных
    // ========================================================================
    ScopeDescriptor {
        scope_id: "u501_import_from_ut",
        scope_type: ScopeType::Usecase,
        label: "Импорт из 1С",
        description: "Загрузка справочников и документов из системы 1С:Управление торговлей",
        icon: "download",
        category: "imports",
        read_label: "Просмотр статуса и истории импорта",
        all_label: "Запуск импорта из 1С",
    },
    ScopeDescriptor {
        scope_id: "u502_import_from_ozon",
        scope_type: ScopeType::Usecase,
        label: "Импорт из Ozon",
        description: "Загрузка заказов, транзакций и товаров с маркетплейса Ozon",
        icon: "download",
        category: "imports",
        read_label: "Просмотр статуса и истории импорта",
        all_label: "Запуск импорта из Ozon",
    },
    ScopeDescriptor {
        scope_id: "u503_import_from_yandex",
        scope_type: ScopeType::Usecase,
        label: "Импорт из Яндекс Маркет",
        description: "Загрузка заказов и финансовых данных с Яндекс Маркет",
        icon: "download",
        category: "imports",
        read_label: "Просмотр статуса и истории импорта",
        all_label: "Запуск импорта из Яндекс Маркет",
    },
    ScopeDescriptor {
        scope_id: "u504_import_from_wildberries",
        scope_type: ScopeType::Usecase,
        label: "Импорт из Wildberries",
        description: "Загрузка заказов, поставок, остатков и рекламных данных с Wildberries",
        icon: "download-cloud",
        category: "imports",
        read_label: "Просмотр статуса и истории импорта",
        all_label: "Запуск импорта из Wildberries",
    },
    ScopeDescriptor {
        scope_id: "u505_match_nomenclature",
        scope_type: ScopeType::Usecase,
        label: "Сопоставление номенклатуры",
        description:
            "Автоматическое сопоставление товаров маркетплейсов с внутренней номенклатурой",
        icon: "git-merge",
        category: "imports",
        read_label: "Просмотр статуса сопоставления",
        all_label: "Запуск сопоставления номенклатуры",
    },
    ScopeDescriptor {
        scope_id: "u506_import_from_lemanapro",
        scope_type: ScopeType::Usecase,
        label: "Импорт из Leroy Merlin",
        description: "Загрузка данных с маркетплейса Leroy Merlin (LemanaПРО)",
        icon: "download",
        category: "imports",
        read_label: "Просмотр статуса и истории импорта",
        all_label: "Запуск импорта из LemanaПРО",
    },
    ScopeDescriptor {
        scope_id: "u507_import_from_erp",
        scope_type: ScopeType::Usecase,
        label: "Импорт из ERP",
        description: "Загрузка данных из корпоративной ERP-системы",
        icon: "download",
        category: "imports",
        read_label: "Просмотр статуса и истории импорта",
        all_label: "Запуск импорта из ERP",
    },
    ScopeDescriptor {
        scope_id: "u508_repost_documents",
        scope_type: ScopeType::Usecase,
        label: "Перепроведение документов",
        description: "Массовое перепроведение агрегатов и проекций после изменения данных",
        icon: "refresh-cw",
        category: "imports",
        read_label: "Просмотр доступных операций и статуса",
        all_label: "Запуск перепроведения",
    },
    // ========================================================================
    // SYSTEM — Системные функции
    // ========================================================================
    ScopeDescriptor {
        scope_id: "general_ledger",
        scope_type: ScopeType::System,
        label: "Общий журнал операций",
        description: "Аналитический журнал всех хозяйственных операций и оборотов по счетам",
        icon: "book-open",
        category: "system",
        read_label: "Просмотр журнала и отчётов",
        all_label: "Просмотр журнала и отчётов",
    },
    ScopeDescriptor {
        scope_id: "data_view",
        scope_type: ScopeType::System,
        label: "Просмотры данных (Data Views)",
        description: "Конфигурируемые представления данных для BI-индикаторов",
        icon: "table",
        category: "system",
        read_label: "Просмотр и вычисление данных",
        all_label: "Просмотр и вычисление данных",
    },
    ScopeDescriptor {
        scope_id: "dashboard",
        scope_type: ScopeType::System,
        label: "Системные дашборды",
        description: "Служебные аналитические дашборды (ежемесячная сводка и пр.)",
        icon: "layout-dashboard",
        category: "system",
        read_label: "Просмотр дашбордов",
        all_label: "Просмотр дашбордов",
    },
    ScopeDescriptor {
        scope_id: "sys_s3_files",
        scope_type: ScopeType::System,
        label: "S3 файлы",
        description: "Управление файлами в Yandex Object Storage",
        icon: "download-cloud",
        category: "system",
        read_label: "Просмотр S3-файлов",
        all_label: "Загрузка, скачивание и удаление S3-файлов",
    },
    // Отдельно от sys_s3_files намеренно: «посмотреть список файлов в бакете» и
    // «перезаписать базу знаний этого инстанса» — права принципиально разной
    // разрушительности, и объединять их в одну галочку нельзя.
    ScopeDescriptor {
        scope_id: "sys_datasets",
        scope_type: ScopeType::System,
        label: "Наборы данных и перенос",
        description: "Выгрузка наборов данных в S3 и восстановление на другом экземпляре",
        icon: "package",
        category: "system",
        read_label: "Просмотр наборов и каталога снапшотов",
        all_label: "Запись снапшотов в S3 и восстановление данных",
    },
];

/// Find a scope descriptor by its scope_id.
pub fn find_scope(scope_id: &str) -> Option<&'static ScopeDescriptor> {
    SCOPE_CATALOG.iter().find(|s| s.scope_id == scope_id)
}
