// ============================================================================
// AUTO-GENERATED FROM metadata.json - DO NOT EDIT MANUALLY
// ============================================================================

#![cfg_attr(rustfmt, rustfmt::skip)]

#![allow(dead_code)]

use crate::shared::metadata::{
    EntityMetadataInfo, EntityType, EntityUiMetadata, EntityAiMetadata,
    FieldMetadata, FieldType, FieldSource, FieldUiMetadata, ValidationRules
};
use crate::shared::access::{EntityAccessMeta, ScopeOperation, AccessMode};

/// Access scope metadata for this entity
pub const ACCESS_META: EntityAccessMeta = EntityAccessMeta {
    scope_id: "a001_connection_1c",
    operations: &[
    ScopeOperation { id: "list", required_mode: AccessMode::Read },
    ScopeOperation { id: "get", required_mode: AccessMode::Read },
    ScopeOperation { id: "upsert", required_mode: AccessMode::All },
    ScopeOperation { id: "delete", required_mode: AccessMode::All }
    ],
};

/// Entity metadata for Connection1CDatabase aggregate
pub const ENTITY_METADATA: EntityMetadataInfo = EntityMetadataInfo {
    schema_version: "1.0",
    entity_type: EntityType::Aggregate,
    entity_name: "Connection1CDatabase",
    entity_index: "a001",
    collection_name: "connection_1c",
    table_name: Some("a001_connection_1c_database"),
    ui: EntityUiMetadata {
        element_name: "Подключение 1С",
        element_name_en: Some("1C Connection"),
        list_name: "Подключения 1С",
        list_name_en: Some("1C Connections"),
        icon: Some("database"),
    },
    ai: EntityAiMetadata {
        description: "Настройки подключения к базе данных 1С:Управление торговлей. Используется для импорта справочников (номенклатура, организации, контрагенты) через OData API. Обычно в системе одно основное подключение, помеченное флагом is_primary.",
        questions: &["Как подключиться к 1С?", "Какие данные импортируются из 1С?", "Как настроить синхронизацию с 1С?", "Почему не работает импорт из 1С?"],
        related: &["a002_organization", "a003_counterparty", "a004_nomenclature"],
        tags: &["ref", "1c"],
        llm_visible: true,
    },
    access: Some(&ACCESS_META),
};

/// Field metadata array
pub const FIELDS: &[FieldMetadata] = &[
    FieldMetadata {
        name: "id",
        rust_type: "Connection1CDatabaseId",
        field_type: FieldType::Primitive,
        source: FieldSource::Base,
        ui: FieldUiMetadata {
            label: "ID",
            label_en: Some("ID"),
            placeholder: None,
            hint: None,
            visible_in_list: false,
            visible_in_form: false,
            widget: None,
            column_width: None,
        },
        validation: ValidationRules {
            required: true,
            min: None,
            max: None,
            min_length: None,
            max_length: None,
            pattern: None,
            custom_error: None,
        },
        ai_hint: None,
        physical: true,
        nested_fields: None,
        ref_aggregate: None,
        enum_values: None,
    },
    FieldMetadata {
        name: "code",
        rust_type: "String",
        field_type: FieldType::Primitive,
        source: FieldSource::Base,
        ui: FieldUiMetadata {
            label: "Код",
            label_en: Some("Code"),
            placeholder: Some("CON-001"),
            hint: Some("Уникальный код подключения"),
            visible_in_list: true,
            visible_in_form: true,
            widget: None,
            column_width: Some(120),
        },
        validation: ValidationRules {
            required: true,
            min: None,
            max: None,
            min_length: None,
            max_length: Some(50),
            pattern: None,
            custom_error: None,
        },
        ai_hint: None,
        physical: true,
        nested_fields: None,
        ref_aggregate: None,
        enum_values: None,
    },
    FieldMetadata {
        name: "description",
        rust_type: "String",
        field_type: FieldType::Primitive,
        source: FieldSource::Base,
        ui: FieldUiMetadata {
            label: "Наименование",
            label_en: Some("Name"),
            placeholder: Some("Основное подключение к 1С"),
            hint: Some("Описательное название подключения"),
            visible_in_list: true,
            visible_in_form: true,
            widget: None,
            column_width: Some(250),
        },
        validation: ValidationRules {
            required: true,
            min: None,
            max: None,
            min_length: Some(3),
            max_length: Some(255),
            pattern: None,
            custom_error: None,
        },
        ai_hint: None,
        physical: true,
        nested_fields: None,
        ref_aggregate: None,
        enum_values: None,
    },
    FieldMetadata {
        name: "comment",
        rust_type: "String",
        field_type: FieldType::Primitive,
        source: FieldSource::Base,
        ui: FieldUiMetadata {
            label: "Комментарий",
            label_en: Some("Comment"),
            placeholder: Some("Дополнительная информация"),
            hint: Some("Произвольный комментарий"),
            visible_in_list: false,
            visible_in_form: true,
            widget: Some("textarea"),
            column_width: None,
        },
        validation: ValidationRules {
            required: false,
            min: None,
            max: None,
            min_length: None,
            max_length: Some(1000),
            pattern: None,
            custom_error: None,
        },
        ai_hint: None,
        physical: true,
        nested_fields: None,
        ref_aggregate: None,
        enum_values: None,
    },
    FieldMetadata {
        name: "url",
        rust_type: "String",
        field_type: FieldType::Primitive,
        source: FieldSource::Specific,
        ui: FieldUiMetadata {
            label: "URL",
            label_en: Some("URL"),
            placeholder: Some("http://192.168.1.10/ut11/odata/standard.odata"),
            hint: Some("HTTP(S) адрес OData сервиса 1С:УТ"),
            visible_in_list: true,
            visible_in_form: true,
            widget: None,
            column_width: Some(300),
        },
        validation: ValidationRules {
            required: true,
            min: None,
            max: None,
            min_length: None,
            max_length: Some(500),
            pattern: Some("^https?://.+"),
            custom_error: Some("URL должен начинаться с http:// или https://"),
        },
        ai_hint: Some("Формат URL: http://сервер/имя_базы/odata/standard.odata. Для работы OData должен быть включен в настройках 1С."),
        physical: true,
        nested_fields: None,
        ref_aggregate: None,
        enum_values: None,
    },
    FieldMetadata {
        name: "login",
        rust_type: "String",
        field_type: FieldType::Primitive,
        source: FieldSource::Specific,
        ui: FieldUiMetadata {
            label: "Логин",
            label_en: Some("Login"),
            placeholder: Some("odata_user"),
            hint: Some("Имя пользователя 1С с правами OData"),
            visible_in_list: true,
            visible_in_form: true,
            widget: None,
            column_width: Some(150),
        },
        validation: ValidationRules {
            required: true,
            min: None,
            max: None,
            min_length: None,
            max_length: Some(100),
            pattern: None,
            custom_error: None,
        },
        ai_hint: Some("Пользователь должен иметь права на чтение справочников и документов через OData в 1С."),
        physical: true,
        nested_fields: None,
        ref_aggregate: None,
        enum_values: None,
    },
    FieldMetadata {
        name: "password",
        rust_type: "String",
        field_type: FieldType::Primitive,
        source: FieldSource::Specific,
        ui: FieldUiMetadata {
            label: "Пароль",
            label_en: Some("Password"),
            placeholder: Some("••••••••"),
            hint: Some("Пароль пользователя 1С"),
            visible_in_list: false,
            visible_in_form: true,
            widget: Some("password"),
            column_width: None,
        },
        validation: ValidationRules {
            required: true,
            min: None,
            max: None,
            min_length: None,
            max_length: Some(100),
            pattern: None,
            custom_error: None,
        },
        ai_hint: None,
        physical: true,
        nested_fields: None,
        ref_aggregate: None,
        enum_values: None,
    },
    FieldMetadata {
        name: "is_primary",
        rust_type: "bool",
        field_type: FieldType::Primitive,
        source: FieldSource::Specific,
        ui: FieldUiMetadata {
            label: "Основное",
            label_en: Some("Primary"),
            placeholder: None,
            hint: Some("Отметить как основное подключение"),
            visible_in_list: true,
            visible_in_form: true,
            widget: Some("checkbox"),
            column_width: Some(100),
        },
        validation: ValidationRules {
            required: false,
            min: None,
            max: None,
            min_length: None,
            max_length: None,
            pattern: None,
            custom_error: None,
        },
        ai_hint: Some("Только одно подключение может быть основным. Импорт данных (u501_import_from_ut) выполняется из основного подключения. При установке флага, он автоматически снимается с других подключений."),
        physical: true,
        nested_fields: None,
        ref_aggregate: None,
        enum_values: None,
    },
];
