//! Каталог загрузок Wildberries.
//!
//! `period` описывает, что бэкенд реально делает с выбранным периодом — это
//! не всегда «дата документа». Проверять по
//! `backend/src/usecases/u504_import_from_wildberries/executor.rs` и
//! `backend/src/shared/marketplaces/wildberries/api_client.rs`.

use crate::usecases::common::{ImportOp, OpGroup, PeriodKind};

pub const OPS: &[ImportOp] = &[
    ImportOp {
        row_id: "a007",
        aggregate: "a007_marketplace_product",
        title: "Товары WB: каталог",
        group: OpGroup::Catalog,
        period: PeriodKind::None,
        period_note: "Выгрузка идёт по курсору, страницами по 100 карточек",
        details: "Загружает карточки товаров продавца из кабинета Wildberries: номенклатурные идентификаторы WB, артикулы, баркоды и другие данные, которые нужны для сопоставления ассортимента внутри системы.",
    },
    ImportOp {
        row_id: "p908",
        aggregate: "p908_wb_goods_prices",
        title: "Товары WB: цены",
        group: OpGroup::Catalog,
        period: PeriodKind::None,
        period_note: "Пагинация limit/offset, снимок текущих цен",
        details: "Загружает актуальные цены и скидки по товарам Wildberries, чтобы в системе были свежие значения по каждой позиции ассортимента и можно было анализировать текущие условия продаж.",
    },
    ImportOp {
        row_id: "a020",
        aggregate: "a020_wb_promotion",
        title: "Товары WB: акции",
        group: OpGroup::Catalog,
        period: PeriodKind::DocDate,
        period_note: "Период = окно календаря акций (startDateTime/endDateTime)",
        details: "Загружает список активных и запланированных акций Wildberries вместе с привязанными товарами, чтобы видеть, какие позиции участвуют в промо и на какой период запланированы изменения.",
    },
    ImportOp {
        row_id: "a015_new",
        aggregate: "a015_wb_orders_new",
        title: "Заказы WB: новые",
        group: OpGroup::Orders,
        period: PeriodKind::DocDate,
        period_note: "Период = дата оформления заказа",
        details: "Загружает новые заказы вскоре после оформления в кабинете Wildberries. Этот режим нужен для оперативной работы с заказами, когда важна скорость появления данных, даже если часть финансовых полей еще недоступна.",
    },
    ImportOp {
        row_id: "a015",
        aggregate: "a015_wb_orders",
        title: "Заказы WB: история",
        group: OpGroup::Orders,
        period: PeriodKind::ChangeDate,
        period_note: "Бэкфилл курсором по lastChangeDate (flag=0), «по» — мягкий стоп",
        details: "Загружает исторические заказы Wildberries с более полным набором данных: ценами, скидками и дополнительными реквизитами. Этот режим подходит для выравнивания и дозагрузки данных за период.",
    },
    ImportOp {
        row_id: "a029",
        aggregate: "a029_wb_supply",
        title: "Поставки WB (FBS)",
        group: OpGroup::Orders,
        period: PeriodKind::ClientFilter,
        period_note: "API отдаёт все поставки, окно применяется к createdAt/closedAt/scanDt",
        details: "Загружает поставки FBS за выбранный период, актуализирует связь уже известных заказов с этими поставками и сохраняет текущий состав поставки без затирания существующих данных. Во время загрузки дополнительно запрашиваются номера стикеров по заказам поставки и сохраняются в составе поставки для колонки «Стикер A-B».",
    },
    ImportOp {
        row_id: "a012",
        aggregate: "a012_wb_sales",
        title: "Продажи WB",
        group: OpGroup::Finance,
        period: PeriodKind::ChangeDate,
        period_note: "flag=0: WB трактует «с» как lastChangeDate, а не дату продажи",
        details: "Загружает продажи и возвраты Wildberries с финансовыми полями, чтобы в системе появились данные для выручки, скидок, комиссий и последующего расчета финансового результата.",
    },
    ImportOp {
        row_id: "a032",
        aggregate: "a032_wb_returns_claims",
        title: "Заявки на возврат WB",
        group: OpGroup::Finance,
        period: PeriodKind::None,
        period_note: "WB отдаёт только последние 14 дней, выбор периода невозможен",
        details: "Загружает заявки покупателей на возврат товара из returns-api.wildberries.ru/api/v1/claims. Опрашиваются активные и архивные заявки. Upsert по (claim_id, connection_id). Требует токена с категорией «Buyers Returns».",
    },
    ImportOp {
        row_id: "p903",
        aggregate: "p903_wb_finance_report",
        title: "Финансы WB: отчет",
        group: OpGroup::Finance,
        period: PeriodKind::ReportPeriod,
        period_note: "Период отчёта реализации, страницы по курсору rrdid",
        details: "Загружает детализированный финансовый отчет Wildberries по выбранному периоду: строки реализации, удержания и прочие финансовые показатели, которые нужны для глубокой сверки расчетов.",
    },
    ImportOp {
        row_id: "a043",
        aggregate: "a043_wb_finance_report",
        title: "Финансы WB: новый Finance API v1",
        group: OpGroup::Finance,
        period: PeriodKind::ReportPeriod,
        period_note: "Период отчёта; начало периода не раньше 01.01.2025",
        details: "Загружает список ежедневных отчётов реализации и полную детализацию каждого reportId в независимый агрегат a043. Не изменяет legacy p903, проводки и сверки. API доступен с 2025-01-01 и ограничен одним запросом в минуту.",
    },
    ImportOp {
        row_id: "p905",
        aggregate: "p905_wb_commission_history",
        title: "Финансы WB: комиссии",
        group: OpGroup::Finance,
        period: PeriodKind::None,
        period_note: "Справочник тарифов выгружается целиком",
        details: "Загружает актуальные ставки комиссий Wildberries по категориям, чтобы система могла использовать свежие правила расчета комиссионной нагрузки по ассортименту.",
    },
    ImportOp {
        row_id: "a027",
        aggregate: "a027_wb_documents",
        title: "Документы WB",
        group: OpGroup::Documents,
        period: PeriodKind::DocDate,
        period_note: "WB не гарантирует фильтр по датам — отбор по дате документа на нашей стороне",
        details: "Загружает входящие документы Wildberries, например акты и накладные, чтобы в системе был единый список доступных документов по кабинету за выбранный период.",
    },
    ImportOp {
        row_id: "wb_advert_csv",
        aggregate: "wb_advert_stats",
        title: "Реклама WB: статистика",
        group: OpGroup::Analytics,
        period: PeriodKind::DocDate,
        period_note: "Период = дни статистики кампаний (beginDate/endDate)",
        details: "Загружает дневную статистику рекламных кампаний Wildberries в документы a026 (по дате и advert_id), с проводками и проекциями. Промежуточный CSV в пайплайне не создаётся.",
    },
    ImportOp {
        row_id: "a036",
        aggregate: "a036_wb_sales_funnel_daily",
        title: "Воронка продаж WB",
        group: OpGroup::Analytics,
        period: PeriodKind::ReportPeriod,
        period_note: "Дни воронки; WB отдаёт примерно последнюю неделю",
        details: "Загружает дневную воронку продаж Wildberries в разрезе номенклатуры (переходы, корзины, заказы, выкупы, конверсии) в документы a036. Один документ на день и кабинет.",
    },
    ImportOp {
        row_id: "a036_history",
        aggregate: "a036_wb_sales_funnel_daily_history",
        title: "Воронка продаж WB: история CSV",
        group: OpGroup::Analytics,
        period: PeriodKind::ReportPeriod,
        period_note: "Асинхронный DETAIL_HISTORY_REPORT за период, агрегация по дням",
        details: "Создаёт асинхронный отчёт DETAIL_HISTORY_REPORT, ожидает готовность и загружает дневную историю в документы a036 за выбранный период. Требуется подписка «Джем». Существующая оперативная загрузка воронки не изменяется.",
    },
    ImportOp {
        row_id: "a037",
        aggregate: "a037_wb_product_snapshot",
        title: "Данные по товарам WB",
        group: OpGroup::Analytics,
        period: PeriodKind::SnapshotDay,
        period_note: "Период — только окно активности товаров; дата документа = сегодня",
        details: "Собирает текущие остатки (склады WB и продавца) и рейтинги товаров Wildberries в документ a037 за сегодняшнюю дату. Данные фиксируются только вперёд — для динамики по дням запускайте ежедневно (или включите задачу task020).",
    },
    ImportOp {
        row_id: "a040",
        aggregate: "a040_wb_search_analytics_daily",
        title: "Поисковая аналитика WB (видимость)",
        group: OpGroup::Analytics,
        period: PeriodKind::SnapshotDay,
        period_note: "Начало периода игнорируется: снимок делается на дату «по»",
        details: "Собирает поисковую аналитику Wildberries в разрезе номенклатуры (видимость товара в выдаче в %, переходы из поиска, средняя позиция в выдаче + топ поисковых запросов) в документ a040 за дату. WB отдаёт только видимость (%), а не счётчик показов — a040 НЕ питает воронку p916 (органические показы там остаются N/A). Требует подписки «Джем» — при отсутствии доступа сбор завершится без данных. Данные фиксируются только вперёд.",
    },
];
