// ============================================================================
// AUTO-GENERATED FROM metadata.json - DO NOT EDIT MANUALLY
// ============================================================================

#![cfg_attr(rustfmt, rustfmt::skip)]

#![allow(dead_code)]

use crate::shared::metadata::{
    EntityMetadataInfo, EntityType, EntityUiMetadata, EntityAiMetadata,
    FieldMetadata, FieldType, FieldSource, FieldUiMetadata, ValidationRules
};
use crate::shared::access::{EntityAccessMeta, ScopeOperation, AccessMode};

/// Access scope metadata for this entity
pub const ACCESS_META: EntityAccessMeta = EntityAccessMeta {
    scope_id: "a038_llm_connection",
    operations: &[
    ScopeOperation { id: "list", required_mode: AccessMode::Read },
    ScopeOperation { id: "get", required_mode: AccessMode::Read },
    ScopeOperation { id: "upsert", required_mode: AccessMode::All },
    ScopeOperation { id: "delete", required_mode: AccessMode::All }
    ],
};

/// Entity metadata for LlmConnection aggregate
pub const ENTITY_METADATA: EntityMetadataInfo = EntityMetadataInfo {
    schema_version: "1.0",
    entity_type: EntityType::Aggregate,
    entity_name: "LlmConnection",
    entity_index: "a038",
    collection_name: "llm_connection",
    table_name: Some("a038_llm_connection"),
    ui: EntityUiMetadata {
        element_name: "Подключение LLM",
        element_name_en: Some("LLM Connection"),
        list_name: "Подключения LLM",
        list_name_en: Some("LLM Connections"),
        icon: Some("plug-connected"),
    },
    ai: EntityAiMetadata {
        description: "Техническое подключение к провайдеру LLM (OpenAI, OpenRouter, DeepSeek). Содержит API-ключ, эндпоинт, параметры модели (temperature, max_tokens) и курируемый список разрешённых моделей (allowed_models). Персона (роль, промпт) вынесена на «виртуального сотрудника» a017, который ссылается на это подключение. Чат работает через сотрудника и переключает модель в пределах allowed_models.",
        questions: &["Какие LLM подключения настроены?", "Как добавить подключение OpenRouter?", "Какие модели разрешены для подключения?", "Как изменить список моделей подключения?"],
        related: &["a018_llm_chat", "a019_llm_artifact"],
        tags: &["llm"],
        llm_visible: true,
    },
    access: Some(&ACCESS_META),
};

/// Field metadata array
pub const FIELDS: &[FieldMetadata] = &[
    FieldMetadata {
        name: "id",
        rust_type: "LlmConnectionId",
        field_type: FieldType::Primitive,
        source: FieldSource::Base,
        ui: FieldUiMetadata {
            label: "ID",
            label_en: Some("ID"),
            placeholder: None,
            hint: None,
            visible_in_list: false,
            visible_in_form: false,
            widget: None,
            column_width: None,
        },
        validation: ValidationRules {
            required: true,
            min: None,
            max: None,
            min_length: None,
            max_length: None,
            pattern: None,
            custom_error: None,
        },
        ai_hint: None,
        physical: true,
        nested_fields: None,
        ref_aggregate: None,
        enum_values: None,
    },
    FieldMetadata {
        name: "code",
        rust_type: "String",
        field_type: FieldType::Primitive,
        source: FieldSource::Base,
        ui: FieldUiMetadata {
            label: "Код",
            label_en: Some("Code"),
            placeholder: Some("OPENROUTER-MAIN"),
            hint: Some("Уникальный код подключения"),
            visible_in_list: true,
            visible_in_form: true,
            widget: None,
            column_width: Some(150),
        },
        validation: ValidationRules {
            required: true,
            min: None,
            max: None,
            min_length: None,
            max_length: Some(50),
            pattern: None,
            custom_error: None,
        },
        ai_hint: None,
        physical: true,
        nested_fields: None,
        ref_aggregate: None,
        enum_values: None,
    },
    FieldMetadata {
        name: "description",
        rust_type: "String",
        field_type: FieldType::Primitive,
        source: FieldSource::Base,
        ui: FieldUiMetadata {
            label: "Наименование",
            label_en: Some("Name"),
            placeholder: Some("OpenRouter основное подключение"),
            hint: Some("Описательное название подключения"),
            visible_in_list: true,
            visible_in_form: true,
            widget: None,
            column_width: Some(250),
        },
        validation: ValidationRules {
            required: true,
            min: None,
            max: None,
            min_length: Some(3),
            max_length: Some(255),
            pattern: None,
            custom_error: None,
        },
        ai_hint: None,
        physical: true,
        nested_fields: None,
        ref_aggregate: None,
        enum_values: None,
    },
    FieldMetadata {
        name: "comment",
        rust_type: "String",
        field_type: FieldType::Primitive,
        source: FieldSource::Base,
        ui: FieldUiMetadata {
            label: "Комментарий",
            label_en: Some("Comment"),
            placeholder: Some("Используется для аналитики продаж"),
            hint: Some("Произвольный комментарий"),
            visible_in_list: false,
            visible_in_form: true,
            widget: Some("textarea"),
            column_width: None,
        },
        validation: ValidationRules {
            required: false,
            min: None,
            max: None,
            min_length: None,
            max_length: Some(1000),
            pattern: None,
            custom_error: None,
        },
        ai_hint: None,
        physical: true,
        nested_fields: None,
        ref_aggregate: None,
        enum_values: None,
    },
    FieldMetadata {
        name: "provider_type",
        rust_type: "String",
        field_type: FieldType::Primitive,
        source: FieldSource::Specific,
        ui: FieldUiMetadata {
            label: "Провайдер",
            label_en: Some("Provider"),
            placeholder: None,
            hint: Some("Тип провайдера LLM"),
            visible_in_list: true,
            visible_in_form: true,
            widget: Some("select"),
            column_width: Some(120),
        },
        validation: ValidationRules {
            required: true,
            min: None,
            max: None,
            min_length: None,
            max_length: None,
            pattern: None,
            custom_error: None,
        },
        ai_hint: Some("Реально поддерживаемые провайдеры: OpenAI (GPT), OpenRouter (кросс-вендорный OpenAI-совместимый роутинг), DeepSeek и Kimi/Moonshot (нативные OpenAI-совместимые API), Ollama (локальная модель на этой машине, ключ не требуется)"),
        physical: true,
        nested_fields: None,
        ref_aggregate: None,
        enum_values: None,
    },
    FieldMetadata {
        name: "api_endpoint",
        rust_type: "String",
        field_type: FieldType::Primitive,
        source: FieldSource::Specific,
        ui: FieldUiMetadata {
            label: "API Endpoint",
            label_en: Some("API Endpoint"),
            placeholder: Some("https://openrouter.ai/api/v1"),
            hint: Some("URL эндпоинта API провайдера"),
            visible_in_list: false,
            visible_in_form: true,
            widget: None,
            column_width: Some(300),
        },
        validation: ValidationRules {
            required: true,
            min: None,
            max: None,
            min_length: None,
            max_length: Some(500),
            pattern: Some("^https?://.+"),
            custom_error: Some("URL должен начинаться с http:// или https://"),
        },
        ai_hint: Some("OpenAI: https://api.openai.com/v1, OpenRouter: https://openrouter.ai/api/v1, DeepSeek: https://api.deepseek.com, Kimi: https://api.moonshot.ai/v1, Ollama: http://localhost:11434/v1"),
        physical: true,
        nested_fields: None,
        ref_aggregate: None,
        enum_values: None,
    },
    FieldMetadata {
        name: "api_key",
        rust_type: "String",
        field_type: FieldType::Primitive,
        source: FieldSource::Specific,
        ui: FieldUiMetadata {
            label: "API Ключ",
            label_en: Some("API Key"),
            placeholder: Some("sk-..."),
            hint: Some("API ключ для аутентификации"),
            visible_in_list: false,
            visible_in_form: true,
            widget: Some("password"),
            column_width: None,
        },
        validation: ValidationRules {
            required: false,
            min: None,
            max: None,
            min_length: None,
            max_length: Some(500),
            pattern: None,
            custom_error: None,
        },
        ai_hint: Some("Хранится в зашифрованном виде. Обязателен для всех провайдеров, кроме локальной Ollama — у неё ключа не существует, поле остаётся пустым."),
        physical: true,
        nested_fields: None,
        ref_aggregate: None,
        enum_values: None,
    },
    FieldMetadata {
        name: "model_name",
        rust_type: "String",
        field_type: FieldType::Primitive,
        source: FieldSource::Specific,
        ui: FieldUiMetadata {
            label: "Модель по умолчанию",
            label_en: Some("Default Model"),
            placeholder: Some("openai/gpt-4o"),
            hint: Some("Модель по умолчанию для новых чатов"),
            visible_in_list: true,
            visible_in_form: true,
            widget: None,
            column_width: Some(150),
        },
        validation: ValidationRules {
            required: true,
            min: None,
            max: None,
            min_length: None,
            max_length: Some(100),
            pattern: None,
            custom_error: None,
        },
        ai_hint: Some("Должна входить в allowed_models. OpenAI: gpt-4o. OpenRouter: openai/gpt-4o, anthropic/claude-sonnet-5, deepseek/deepseek-chat. DeepSeek (нативно): deepseek-chat, deepseek-reasoner"),
        physical: true,
        nested_fields: None,
        ref_aggregate: None,
        enum_values: None,
    },
    FieldMetadata {
        name: "available_models",
        rust_type: "String",
        field_type: FieldType::Primitive,
        source: FieldSource::Specific,
        ui: FieldUiMetadata {
            label: "Доступные модели",
            label_en: Some("Available Models"),
            placeholder: None,
            hint: Some("JSON список моделей из API (кэш fetch-models)"),
            visible_in_list: false,
            visible_in_form: false,
            widget: Some("textarea"),
            column_width: None,
        },
        validation: ValidationRules {
            required: false,
            min: None,
            max: None,
            min_length: None,
            max_length: None,
            pattern: None,
            custom_error: None,
        },
        ai_hint: Some("JSON массив объектов с полями id, created, owned_by. Загружается из /v1/models API провайдера."),
        physical: true,
        nested_fields: None,
        ref_aggregate: None,
        enum_values: None,
    },
    FieldMetadata {
        name: "allowed_models",
        rust_type: "String",
        field_type: FieldType::Primitive,
        source: FieldSource::Specific,
        ui: FieldUiMetadata {
            label: "Разрешённые модели",
            label_en: Some("Allowed Models"),
            placeholder: None,
            hint: Some("Курируемый короткий список моделей (JSON-массив id)"),
            visible_in_list: false,
            visible_in_form: true,
            widget: Some("textarea"),
            column_width: None,
        },
        validation: ValidationRules {
            required: false,
            min: None,
            max: None,
            min_length: None,
            max_length: None,
            pattern: None,
            custom_error: None,
        },
        ai_hint: Some("JSON массив model_id — подмножество available_models. Только эти модели можно выбрать в чате. Держите 3-8 технически совместимых и целесообразных моделей."),
        physical: true,
        nested_fields: None,
        ref_aggregate: None,
        enum_values: None,
    },
    FieldMetadata {
        name: "temperature",
        rust_type: "f64",
        field_type: FieldType::Primitive,
        source: FieldSource::Specific,
        ui: FieldUiMetadata {
            label: "Temperature",
            label_en: Some("Temperature"),
            placeholder: Some("0.7"),
            hint: Some("Креативность ответов (0.0-2.0)"),
            visible_in_list: false,
            visible_in_form: true,
            widget: None,
            column_width: None,
        },
        validation: ValidationRules {
            required: true,
            min: Some(0.0),
            max: Some(2.0),
            min_length: None,
            max_length: None,
            pattern: None,
            custom_error: None,
        },
        ai_hint: Some("0.0 - детерминированно, 1.0 - сбалансированно, 2.0 - максимально креативно"),
        physical: true,
        nested_fields: None,
        ref_aggregate: None,
        enum_values: None,
    },
    FieldMetadata {
        name: "max_tokens",
        rust_type: "i32",
        field_type: FieldType::Primitive,
        source: FieldSource::Specific,
        ui: FieldUiMetadata {
            label: "Max Tokens",
            label_en: Some("Max Tokens"),
            placeholder: Some("4096"),
            hint: Some("Максимальная длина ответа"),
            visible_in_list: false,
            visible_in_form: true,
            widget: None,
            column_width: None,
        },
        validation: ValidationRules {
            required: true,
            min: Some(256.0),
            max: Some(128000.0),
            min_length: None,
            max_length: None,
            pattern: None,
            custom_error: None,
        },
        ai_hint: Some("GPT-4o поддерживает до 128k токенов"),
        physical: true,
        nested_fields: None,
        ref_aggregate: None,
        enum_values: None,
    },
    FieldMetadata {
        name: "context_window",
        rust_type: "i32",
        field_type: FieldType::Primitive,
        source: FieldSource::Specific,
        ui: FieldUiMetadata {
            label: "Размер контекста",
            label_en: Some("Context window"),
            placeholder: Some("160000"),
            hint: Some("Окно контекста модели в токенах — из него считается бюджет истории чата"),
            visible_in_list: false,
            visible_in_form: true,
            widget: None,
            column_width: None,
        },
        validation: ValidationRules {
            required: true,
            min: Some(4096.0),
            max: Some(2000000.0),
            min_length: None,
            max_length: None,
            pattern: None,
            custom_error: None,
        },
        ai_hint: Some("Бюджет компакции истории = context_window * 3/4. Для локальной Ollama значение должно совпадать с фактическим num_ctx сервера (OLLAMA_CONTEXT_LENGTH), иначе промпт будет молча обрезаться."),
        physical: true,
        nested_fields: None,
        ref_aggregate: None,
        enum_values: None,
    },
    FieldMetadata {
        name: "is_primary",
        rust_type: "bool",
        field_type: FieldType::Primitive,
        source: FieldSource::Specific,
        ui: FieldUiMetadata {
            label: "Основное",
            label_en: Some("Primary"),
            placeholder: None,
            hint: Some("Использовать по умолчанию"),
            visible_in_list: true,
            visible_in_form: true,
            widget: Some("checkbox"),
            column_width: Some(100),
        },
        validation: ValidationRules {
            required: false,
            min: None,
            max: None,
            min_length: None,
            max_length: None,
            pattern: None,
            custom_error: None,
        },
        ai_hint: Some("Только одно подключение может быть основным. При установке флага автоматически снимается с других."),
        physical: true,
        nested_fields: None,
        ref_aggregate: None,
        enum_values: None,
    },
    FieldMetadata {
        name: "price_in_per_mtok",
        rust_type: "Option<f64>",
        field_type: FieldType::Primitive,
        source: FieldSource::Specific,
        ui: FieldUiMetadata {
            label: "Цена входа за 1M токенов",
            label_en: Some("Input price per 1M tokens"),
            placeholder: Some("3.0"),
            hint: Some("Ставка тарификации входных токенов. Пусто — стоимость не считается"),
            visible_in_list: false,
            visible_in_form: true,
            widget: None,
            column_width: None,
        },
        validation: ValidationRules {
            required: false,
            min: Some(0.0),
            max: None,
            min_length: None,
            max_length: None,
            pattern: None,
            custom_error: None,
        },
        ai_hint: Some("Прайс за миллион токенов в валюте currency. Пустое поле означает «прайс не задан» — стоимость прогонов по этому подключению не рассчитывается. Явный 0 — это реальная цена (локальная модель)."),
        physical: true,
        nested_fields: None,
        ref_aggregate: None,
        enum_values: None,
    },
    FieldMetadata {
        name: "price_out_per_mtok",
        rust_type: "Option<f64>",
        field_type: FieldType::Primitive,
        source: FieldSource::Specific,
        ui: FieldUiMetadata {
            label: "Цена выхода за 1M токенов",
            label_en: Some("Output price per 1M tokens"),
            placeholder: Some("15.0"),
            hint: Some("Ставка тарификации выходных токенов"),
            visible_in_list: false,
            visible_in_form: true,
            widget: None,
            column_width: None,
        },
        validation: ValidationRules {
            required: false,
            min: Some(0.0),
            max: None,
            min_length: None,
            max_length: None,
            pattern: None,
            custom_error: None,
        },
        ai_hint: Some("Выходные токены почти всегда дороже входных — считать стоимость по одной усреднённой ставке нельзя."),
        physical: true,
        nested_fields: None,
        ref_aggregate: None,
        enum_values: None,
    },
    FieldMetadata {
        name: "price_cached_per_mtok",
        rust_type: "Option<f64>",
        field_type: FieldType::Primitive,
        source: FieldSource::Specific,
        ui: FieldUiMetadata {
            label: "Цена кэш-входа за 1M токенов",
            label_en: Some("Cached input price per 1M tokens"),
            placeholder: Some("0.3"),
            hint: Some("Пусто — скидки нет, кэш считается по входной ставке"),
            visible_in_list: false,
            visible_in_form: true,
            widget: None,
            column_width: None,
        },
        validation: ValidationRules {
            required: false,
            min: Some(0.0),
            max: None,
            min_length: None,
            max_length: None,
            pattern: None,
            custom_error: None,
        },
        ai_hint: Some("Кэшированные входные токены — подмножество входных, а не добавка. Пустое поле трактуется как «скидки нет»: незаполненный прайс не должен занижать стоимость."),
        physical: true,
        nested_fields: None,
        ref_aggregate: None,
        enum_values: None,
    },
    FieldMetadata {
        name: "currency",
        rust_type: "Option<String>",
        field_type: FieldType::Primitive,
        source: FieldSource::Specific,
        ui: FieldUiMetadata {
            label: "Валюта прайса",
            label_en: Some("Price currency"),
            placeholder: Some("RUB"),
            hint: Some("Валюта ставок: RUB, USD, …"),
            visible_in_list: false,
            visible_in_form: true,
            widget: None,
            column_width: None,
        },
        validation: ValidationRules {
            required: false,
            min: None,
            max: None,
            min_length: None,
            max_length: Some(8),
            pattern: None,
            custom_error: None,
        },
        ai_hint: Some("Конвертацией курсов подсистема стоимости не занимается: суммы в разных валютах не смешиваются, а разделяются в отчёте."),
        physical: true,
        nested_fields: None,
        ref_aggregate: None,
        enum_values: None,
    },
];
