// ============================================================================
// AUTO-GENERATED FROM metadata.json - DO NOT EDIT MANUALLY
// ============================================================================

#![cfg_attr(rustfmt, rustfmt::skip)]

#![allow(dead_code)]

use crate::shared::metadata::{
    EntityMetadataInfo, EntityType, EntityUiMetadata, EntityAiMetadata,
    FieldMetadata, FieldType, FieldSource, FieldUiMetadata, ValidationRules
};
use crate::shared::access::{EntityAccessMeta, ScopeOperation, AccessMode};

/// Access scope metadata for this entity
pub const ACCESS_META: EntityAccessMeta = EntityAccessMeta {
    scope_id: "a018_llm_chat",
    operations: &[
    ScopeOperation { id: "list", required_mode: AccessMode::Read },
    ScopeOperation { id: "get", required_mode: AccessMode::Read },
    ScopeOperation { id: "upsert", required_mode: AccessMode::All },
    ScopeOperation { id: "delete", required_mode: AccessMode::All }
    ],
};

/// Entity metadata for LlmChat aggregate
pub const ENTITY_METADATA: EntityMetadataInfo = EntityMetadataInfo {
    schema_version: "1.0",
    entity_type: EntityType::Aggregate,
    entity_name: "LlmChat",
    entity_index: "a018",
    collection_name: "llm_chat",
    table_name: Some("a018_llm_chat"),
    ui: EntityUiMetadata {
        element_name: "Чат LLM",
        element_name_en: Some("LLM Chat"),
        list_name: "Чаты LLM",
        list_name_en: Some("LLM Chats"),
        icon: Some("message-square"),
    },
    ai: EntityAiMetadata {
        description: "Сессии чатов с LLM агентами. Содержит историю диалогов с языковыми моделями, включая сообщения пользователя и ответы ассистента. Каждый чат связан с конкретным агентом (a017_llm_agent).",
        questions: &["Какие чаты существуют?", "Как создать новый чат?", "Как посмотреть историю сообщений чата?", "Какой агент используется в чате?"],
        related: &["a017_llm_agent", "a019_llm_artifact"],
        tags: &["llm"],
        llm_visible: true,
    },
    access: Some(&ACCESS_META),
};

/// Field metadata array
pub const FIELDS: &[FieldMetadata] = &[
    FieldMetadata {
        name: "id",
        rust_type: "LlmChatId",
        field_type: FieldType::Primitive,
        source: FieldSource::Base,
        ui: FieldUiMetadata {
            label: "ID",
            label_en: Some("ID"),
            placeholder: None,
            hint: None,
            visible_in_list: false,
            visible_in_form: false,
            widget: None,
            column_width: None,
        },
        validation: ValidationRules {
            required: true,
            min: None,
            max: None,
            min_length: None,
            max_length: None,
            pattern: None,
            custom_error: None,
        },
        ai_hint: None,
        physical: true,
        nested_fields: None,
        ref_aggregate: None,
        enum_values: None,
    },
    FieldMetadata {
        name: "code",
        rust_type: "String",
        field_type: FieldType::Primitive,
        source: FieldSource::Base,
        ui: FieldUiMetadata {
            label: "Код",
            label_en: Some("Code"),
            placeholder: Some("CHAT-001"),
            hint: Some("Уникальный код чата"),
            visible_in_list: true,
            visible_in_form: true,
            widget: None,
            column_width: Some(150),
        },
        validation: ValidationRules {
            required: true,
            min: None,
            max: None,
            min_length: None,
            max_length: Some(50),
            pattern: None,
            custom_error: None,
        },
        ai_hint: None,
        physical: true,
        nested_fields: None,
        ref_aggregate: None,
        enum_values: None,
    },
    FieldMetadata {
        name: "description",
        rust_type: "String",
        field_type: FieldType::Primitive,
        source: FieldSource::Base,
        ui: FieldUiMetadata {
            label: "Наименование",
            label_en: Some("Name"),
            placeholder: Some("Анализ продаж за январь"),
            hint: Some("Описательное название чата"),
            visible_in_list: true,
            visible_in_form: true,
            widget: None,
            column_width: Some(300),
        },
        validation: ValidationRules {
            required: true,
            min: None,
            max: None,
            min_length: Some(3),
            max_length: Some(500),
            pattern: None,
            custom_error: None,
        },
        ai_hint: None,
        physical: true,
        nested_fields: None,
        ref_aggregate: None,
        enum_values: None,
    },
    FieldMetadata {
        name: "comment",
        rust_type: "Option<String>",
        field_type: FieldType::Primitive,
        source: FieldSource::Base,
        ui: FieldUiMetadata {
            label: "Комментарий",
            label_en: Some("Comment"),
            placeholder: Some("Дополнительная информация"),
            hint: Some("Произвольный комментарий"),
            visible_in_list: false,
            visible_in_form: true,
            widget: None,
            column_width: None,
        },
        validation: ValidationRules {
            required: false,
            min: None,
            max: None,
            min_length: None,
            max_length: Some(1000),
            pattern: None,
            custom_error: None,
        },
        ai_hint: None,
        physical: true,
        nested_fields: None,
        ref_aggregate: None,
        enum_values: None,
    },
    FieldMetadata {
        name: "agent_id",
        rust_type: "LlmAgentId",
        field_type: FieldType::AggregateRef,
        source: FieldSource::Specific,
        ui: FieldUiMetadata {
            label: "Агент LLM",
            label_en: Some("LLM Agent"),
            placeholder: None,
            hint: Some("Какой агент используется для этого чата"),
            visible_in_list: true,
            visible_in_form: true,
            widget: Some("select"),
            column_width: Some(200),
        },
        validation: ValidationRules {
            required: true,
            min: None,
            max: None,
            min_length: None,
            max_length: None,
            pattern: None,
            custom_error: None,
        },
        ai_hint: Some("Ссылка на агента LLM (a017_llm_agent), который используется для генерации ответов в этом чате"),
        physical: true,
        nested_fields: None,
        ref_aggregate: Some("a017_llm_agent"),
        enum_values: None,
    },
    FieldMetadata {
        name: "model_name",
        rust_type: "String",
        field_type: FieldType::Primitive,
        source: FieldSource::Specific,
        ui: FieldUiMetadata {
            label: "Модель по умолчанию",
            label_en: Some("Default Model"),
            placeholder: Some("gpt-4o"),
            hint: Some("Модель LLM, используемая по умолчанию для сообщений этого чата"),
            visible_in_list: true,
            visible_in_form: true,
            widget: None,
            column_width: Some(150),
        },
        validation: ValidationRules {
            required: true,
            min: None,
            max: None,
            min_length: None,
            max_length: Some(100),
            pattern: None,
            custom_error: None,
        },
        ai_hint: Some("Название модели LLM (например, gpt-4o, gpt-4-turbo), которая будет использоваться для генерации ответов, если не переопределена в конкретном сообщении"),
        physical: true,
        nested_fields: None,
        ref_aggregate: None,
        enum_values: None,
    },
    FieldMetadata {
        name: "created_at",
        rust_type: "DateTime<Utc>",
        field_type: FieldType::Primitive,
        source: FieldSource::Metadata,
        ui: FieldUiMetadata {
            label: "Создан",
            label_en: Some("Created"),
            placeholder: None,
            hint: None,
            visible_in_list: true,
            visible_in_form: false,
            widget: None,
            column_width: Some(180),
        },
        validation: ValidationRules {
            required: true,
            min: None,
            max: None,
            min_length: None,
            max_length: None,
            pattern: None,
            custom_error: None,
        },
        ai_hint: None,
        physical: true,
        nested_fields: None,
        ref_aggregate: None,
        enum_values: None,
    },
    FieldMetadata {
        name: "updated_at",
        rust_type: "DateTime<Utc>",
        field_type: FieldType::Primitive,
        source: FieldSource::Metadata,
        ui: FieldUiMetadata {
            label: "Обновлён",
            label_en: Some("Updated"),
            placeholder: None,
            hint: None,
            visible_in_list: false,
            visible_in_form: false,
            widget: None,
            column_width: None,
        },
        validation: ValidationRules {
            required: true,
            min: None,
            max: None,
            min_length: None,
            max_length: None,
            pattern: None,
            custom_error: None,
        },
        ai_hint: None,
        physical: true,
        nested_fields: None,
        ref_aggregate: None,
        enum_values: None,
    },
    FieldMetadata {
        name: "is_deleted",
        rust_type: "bool",
        field_type: FieldType::Primitive,
        source: FieldSource::Metadata,
        ui: FieldUiMetadata {
            label: "Удалён",
            label_en: Some("Deleted"),
            placeholder: None,
            hint: None,
            visible_in_list: false,
            visible_in_form: false,
            widget: None,
            column_width: None,
        },
        validation: ValidationRules {
            required: true,
            min: None,
            max: None,
            min_length: None,
            max_length: None,
            pattern: None,
            custom_error: None,
        },
        ai_hint: None,
        physical: true,
        nested_fields: None,
        ref_aggregate: None,
        enum_values: None,
    },
    FieldMetadata {
        name: "version",
        rust_type: "i32",
        field_type: FieldType::Primitive,
        source: FieldSource::Metadata,
        ui: FieldUiMetadata {
            label: "Версия",
            label_en: Some("Version"),
            placeholder: None,
            hint: None,
            visible_in_list: false,
            visible_in_form: false,
            widget: None,
            column_width: None,
        },
        validation: ValidationRules {
            required: true,
            min: None,
            max: None,
            min_length: None,
            max_length: None,
            pattern: None,
            custom_error: None,
        },
        ai_hint: None,
        physical: true,
        nested_fields: None,
        ref_aggregate: None,
        enum_values: None,
    },
];
