// ============================================================================
// AUTO-GENERATED FROM metadata.json - DO NOT EDIT MANUALLY
// ============================================================================

#![cfg_attr(rustfmt, rustfmt::skip)]

#![allow(dead_code)]

use crate::shared::metadata::{
    EntityMetadataInfo, EntityType, EntityUiMetadata, EntityAiMetadata,
    FieldMetadata, FieldType, FieldSource, FieldUiMetadata, ValidationRules
};
use crate::shared::access::{EntityAccessMeta, ScopeOperation, AccessMode};

/// Access scope metadata for this entity
pub const ACCESS_META: EntityAccessMeta = EntityAccessMeta {
    scope_id: "a025_bi_dashboard",
    operations: &[
    ScopeOperation { id: "list", required_mode: AccessMode::Read },
    ScopeOperation { id: "get", required_mode: AccessMode::Read },
    ScopeOperation { id: "upsert", required_mode: AccessMode::All },
    ScopeOperation { id: "delete", required_mode: AccessMode::All }
    ],
};

/// Entity metadata for BiDashboard aggregate
pub const ENTITY_METADATA: EntityMetadataInfo = EntityMetadataInfo {
    schema_version: "1.0",
    entity_type: EntityType::Aggregate,
    entity_name: "BiDashboard",
    entity_index: "a025",
    collection_name: "bi_dashboard",
    table_name: Some("a025_bi_dashboard"),
    ui: EntityUiMetadata {
        element_name: "BI Дашборд",
        element_name_en: Some("BI Dashboard"),
        list_name: "BI Дашборды",
        list_name_en: Some("BI Dashboards"),
        icon: Some("layout-dashboard"),
    },
    ai: EntityAiMetadata {
        description: "BI-дашборды. Каждый дашборд объединяет набор BI-индикаторов (a024), сгруппированных по категориям в дерево. Содержит глобальные фильтры, оценку пользователя (1-5 звёзд) и статус. Дашборды могут быть персональными или публичными.",
        questions: &["Какие дашборды доступны в системе?", "Как создать новый BI дашборд?", "Как добавить индикатор в дашборд?", "Как организовать индикаторы по категориям?", "Как настроить глобальные фильтры для дашборда?"],
        related: &["a024_bi_indicator"],
        tags: &["bi", "dashboard"],
        llm_visible: true,
    },
    access: Some(&ACCESS_META),
};

/// Field metadata array
pub const FIELDS: &[FieldMetadata] = &[
    FieldMetadata {
        name: "id",
        rust_type: "BiDashboardId",
        field_type: FieldType::Primitive,
        source: FieldSource::Base,
        ui: FieldUiMetadata {
            label: "ID",
            label_en: Some("ID"),
            placeholder: None,
            hint: None,
            visible_in_list: false,
            visible_in_form: false,
            widget: None,
            column_width: None,
        },
        validation: ValidationRules {
            required: true,
            min: None,
            max: None,
            min_length: None,
            max_length: None,
            pattern: None,
            custom_error: None,
        },
        ai_hint: None,
        physical: true,
        nested_fields: None,
        ref_aggregate: None,
        enum_values: None,
    },
    FieldMetadata {
        name: "code",
        rust_type: "String",
        field_type: FieldType::Primitive,
        source: FieldSource::Base,
        ui: FieldUiMetadata {
            label: "Код",
            label_en: Some("Code"),
            placeholder: Some("DASH-001"),
            hint: Some("Уникальный код дашборда"),
            visible_in_list: true,
            visible_in_form: true,
            widget: Some("text"),
            column_width: Some(120),
        },
        validation: ValidationRules {
            required: true,
            min: None,
            max: None,
            min_length: None,
            max_length: Some(50),
            pattern: None,
            custom_error: None,
        },
        ai_hint: None,
        physical: true,
        nested_fields: None,
        ref_aggregate: None,
        enum_values: None,
    },
    FieldMetadata {
        name: "description",
        rust_type: "String",
        field_type: FieldType::Primitive,
        source: FieldSource::Base,
        ui: FieldUiMetadata {
            label: "Наименование",
            label_en: Some("Name"),
            placeholder: Some("Операционный дашборд"),
            hint: Some("Название дашборда"),
            visible_in_list: true,
            visible_in_form: true,
            widget: Some("text"),
            column_width: Some(280),
        },
        validation: ValidationRules {
            required: true,
            min: None,
            max: None,
            min_length: Some(2),
            max_length: Some(500),
            pattern: None,
            custom_error: None,
        },
        ai_hint: None,
        physical: true,
        nested_fields: None,
        ref_aggregate: None,
        enum_values: None,
    },
    FieldMetadata {
        name: "comment",
        rust_type: "Option<String>",
        field_type: FieldType::Primitive,
        source: FieldSource::Base,
        ui: FieldUiMetadata {
            label: "Комментарий",
            label_en: Some("Comment"),
            placeholder: Some("Описание дашборда и его назначения"),
            hint: None,
            visible_in_list: false,
            visible_in_form: true,
            widget: Some("textarea"),
            column_width: None,
        },
        validation: ValidationRules {
            required: false,
            min: None,
            max: None,
            min_length: None,
            max_length: Some(2000),
            pattern: None,
            custom_error: None,
        },
        ai_hint: None,
        physical: true,
        nested_fields: None,
        ref_aggregate: None,
        enum_values: None,
    },
    FieldMetadata {
        name: "status",
        rust_type: "String",
        field_type: FieldType::Enum,
        source: FieldSource::Specific,
        ui: FieldUiMetadata {
            label: "Статус",
            label_en: Some("Status"),
            placeholder: None,
            hint: None,
            visible_in_list: true,
            visible_in_form: true,
            widget: Some("select"),
            column_width: Some(100),
        },
        validation: ValidationRules {
            required: true,
            min: None,
            max: None,
            min_length: None,
            max_length: None,
            pattern: None,
            custom_error: None,
        },
        ai_hint: Some("Статус дашборда: draft (черновик), active (активен), archived (в архиве)"),
        physical: true,
        nested_fields: None,
        ref_aggregate: None,
        enum_values: Some(&["draft", "active", "archived"]),
    },
    FieldMetadata {
        name: "owner_user_id",
        rust_type: "String",
        field_type: FieldType::Primitive,
        source: FieldSource::Specific,
        ui: FieldUiMetadata {
            label: "Владелец",
            label_en: Some("Owner"),
            placeholder: None,
            hint: None,
            visible_in_list: true,
            visible_in_form: true,
            widget: Some("text"),
            column_width: Some(150),
        },
        validation: ValidationRules {
            required: true,
            min: None,
            max: None,
            min_length: None,
            max_length: None,
            pattern: None,
            custom_error: None,
        },
        ai_hint: Some("ID пользователя-владельца дашборда"),
        physical: true,
        nested_fields: None,
        ref_aggregate: None,
        enum_values: None,
    },
    FieldMetadata {
        name: "is_public",
        rust_type: "bool",
        field_type: FieldType::Primitive,
        source: FieldSource::Specific,
        ui: FieldUiMetadata {
            label: "Публичный",
            label_en: Some("Public"),
            placeholder: None,
            hint: Some("Доступен другим пользователям"),
            visible_in_list: true,
            visible_in_form: true,
            widget: Some("checkbox"),
            column_width: Some(90),
        },
        validation: ValidationRules {
            required: true,
            min: None,
            max: None,
            min_length: None,
            max_length: None,
            pattern: None,
            custom_error: None,
        },
        ai_hint: None,
        physical: true,
        nested_fields: None,
        ref_aggregate: None,
        enum_values: None,
    },
    FieldMetadata {
        name: "rating",
        rust_type: "Option<u8>",
        field_type: FieldType::Primitive,
        source: FieldSource::Specific,
        ui: FieldUiMetadata {
            label: "Оценка",
            label_en: Some("Rating"),
            placeholder: None,
            hint: Some("Оценка дашборда от 1 до 5 звёзд"),
            visible_in_list: true,
            visible_in_form: true,
            widget: Some("rate"),
            column_width: Some(120),
        },
        validation: ValidationRules {
            required: false,
            min: None,
            max: None,
            min_length: None,
            max_length: None,
            pattern: None,
            custom_error: None,
        },
        ai_hint: Some("Оценка пользователя: 1-5 звёзд, null = не оценён"),
        physical: true,
        nested_fields: None,
        ref_aggregate: None,
        enum_values: None,
    },
    FieldMetadata {
        name: "layout_json",
        rust_type: "DashboardLayout",
        field_type: FieldType::NestedStruct,
        source: FieldSource::Specific,
        ui: FieldUiMetadata {
            label: "Раскладка",
            label_en: Some("Layout"),
            placeholder: None,
            hint: Some("Дерево групп с индикаторами"),
            visible_in_list: false,
            visible_in_form: true,
            widget: Some("tree_editor"),
            column_width: None,
        },
        validation: ValidationRules {
            required: false,
            min: None,
            max: None,
            min_length: None,
            max_length: None,
            pattern: None,
            custom_error: None,
        },
        ai_hint: Some("Иерархическое дерево категорий (DashboardGroup) с индикаторами (DashboardItem)"),
        physical: true,
        nested_fields: None,
        ref_aggregate: None,
        enum_values: None,
    },
    FieldMetadata {
        name: "global_filters_json",
        rust_type: "Vec<FilterRef>",
        field_type: FieldType::NestedTable,
        source: FieldSource::Specific,
        ui: FieldUiMetadata {
            label: "Фильтры",
            label_en: Some("Filters"),
            placeholder: None,
            hint: Some("Фильтры, применяемые ко всем индикаторам дашборда"),
            visible_in_list: false,
            visible_in_form: true,
            widget: Some("table"),
            column_width: None,
        },
        validation: ValidationRules {
            required: false,
            min: None,
            max: None,
            min_length: None,
            max_length: None,
            pattern: None,
            custom_error: None,
        },
        ai_hint: Some("Список FilterRef, связывающих дашборд с глобальным реестром фильтров"),
        physical: true,
        nested_fields: None,
        ref_aggregate: None,
        enum_values: None,
    },
    FieldMetadata {
        name: "created_by",
        rust_type: "Option<String>",
        field_type: FieldType::Primitive,
        source: FieldSource::Specific,
        ui: FieldUiMetadata {
            label: "Создал",
            label_en: Some("Created By"),
            placeholder: None,
            hint: None,
            visible_in_list: false,
            visible_in_form: false,
            widget: None,
            column_width: None,
        },
        validation: ValidationRules {
            required: false,
            min: None,
            max: None,
            min_length: None,
            max_length: None,
            pattern: None,
            custom_error: None,
        },
        ai_hint: None,
        physical: true,
        nested_fields: None,
        ref_aggregate: None,
        enum_values: None,
    },
    FieldMetadata {
        name: "updated_by",
        rust_type: "Option<String>",
        field_type: FieldType::Primitive,
        source: FieldSource::Specific,
        ui: FieldUiMetadata {
            label: "Обновил",
            label_en: Some("Updated By"),
            placeholder: None,
            hint: None,
            visible_in_list: false,
            visible_in_form: false,
            widget: None,
            column_width: None,
        },
        validation: ValidationRules {
            required: false,
            min: None,
            max: None,
            min_length: None,
            max_length: None,
            pattern: None,
            custom_error: None,
        },
        ai_hint: None,
        physical: true,
        nested_fields: None,
        ref_aggregate: None,
        enum_values: None,
    },
    FieldMetadata {
        name: "created_at",
        rust_type: "DateTime<Utc>",
        field_type: FieldType::Primitive,
        source: FieldSource::Metadata,
        ui: FieldUiMetadata {
            label: "Создан",
            label_en: Some("Created"),
            placeholder: None,
            hint: None,
            visible_in_list: true,
            visible_in_form: false,
            widget: None,
            column_width: Some(160),
        },
        validation: ValidationRules {
            required: true,
            min: None,
            max: None,
            min_length: None,
            max_length: None,
            pattern: None,
            custom_error: None,
        },
        ai_hint: None,
        physical: true,
        nested_fields: None,
        ref_aggregate: None,
        enum_values: None,
    },
    FieldMetadata {
        name: "updated_at",
        rust_type: "DateTime<Utc>",
        field_type: FieldType::Primitive,
        source: FieldSource::Metadata,
        ui: FieldUiMetadata {
            label: "Обновлён",
            label_en: Some("Updated"),
            placeholder: None,
            hint: None,
            visible_in_list: false,
            visible_in_form: false,
            widget: None,
            column_width: None,
        },
        validation: ValidationRules {
            required: true,
            min: None,
            max: None,
            min_length: None,
            max_length: None,
            pattern: None,
            custom_error: None,
        },
        ai_hint: None,
        physical: true,
        nested_fields: None,
        ref_aggregate: None,
        enum_values: None,
    },
    FieldMetadata {
        name: "is_deleted",
        rust_type: "bool",
        field_type: FieldType::Primitive,
        source: FieldSource::Metadata,
        ui: FieldUiMetadata {
            label: "Удалён",
            label_en: Some("Deleted"),
            placeholder: None,
            hint: None,
            visible_in_list: false,
            visible_in_form: false,
            widget: None,
            column_width: None,
        },
        validation: ValidationRules {
            required: true,
            min: None,
            max: None,
            min_length: None,
            max_length: None,
            pattern: None,
            custom_error: None,
        },
        ai_hint: None,
        physical: true,
        nested_fields: None,
        ref_aggregate: None,
        enum_values: None,
    },
    FieldMetadata {
        name: "version",
        rust_type: "i32",
        field_type: FieldType::Primitive,
        source: FieldSource::Metadata,
        ui: FieldUiMetadata {
            label: "Версия",
            label_en: Some("Version"),
            placeholder: None,
            hint: None,
            visible_in_list: false,
            visible_in_form: false,
            widget: None,
            column_width: None,
        },
        validation: ValidationRules {
            required: true,
            min: None,
            max: None,
            min_length: None,
            max_length: None,
            pattern: None,
            custom_error: None,
        },
        ai_hint: None,
        physical: true,
        nested_fields: None,
        ref_aggregate: None,
        enum_values: None,
    },
];
