// ============================================================================
// AUTO-GENERATED FROM metadata.json - DO NOT EDIT MANUALLY
// ============================================================================

#![cfg_attr(rustfmt, rustfmt::skip)]

#![allow(dead_code)]

use crate::shared::metadata::{
    EntityMetadataInfo, EntityType, EntityUiMetadata, EntityAiMetadata,
    FieldMetadata, FieldType, FieldSource, FieldUiMetadata, ValidationRules
};
use crate::shared::access::{EntityAccessMeta, ScopeOperation, AccessMode};

/// Access scope metadata for this entity
pub const ACCESS_META: EntityAccessMeta = EntityAccessMeta {
    scope_id: "a017_llm_agent",
    operations: &[
    ScopeOperation { id: "list", required_mode: AccessMode::Read },
    ScopeOperation { id: "get", required_mode: AccessMode::Read },
    ScopeOperation { id: "upsert", required_mode: AccessMode::All },
    ScopeOperation { id: "delete", required_mode: AccessMode::All }
    ],
};

/// Entity metadata for LlmAgent aggregate
pub const ENTITY_METADATA: EntityMetadataInfo = EntityMetadataInfo {
    schema_version: "1.0",
    entity_type: EntityType::Aggregate,
    entity_name: "LlmAgent",
    entity_index: "a017",
    collection_name: "llm_agent",
    table_name: Some("a017_llm_agent"),
    ui: EntityUiMetadata {
        element_name: "AI-сотрудник",
        element_name_en: Some("AI Employee"),
        list_name: "AI-сотрудники",
        list_name_en: Some("AI Employees"),
        icon: Some("robot"),
    },
    ai: EntityAiMetadata {
        description: "Виртуальный сотрудник (AI-агент): имя, аватар, почта, специализация (agent_type — определяет навыки), должностные обязанности (system_prompt) и расписание. Работает через привязанное техническое подключение a038 (connection_id), из которого берёт провайдера/креды/тюнинг. Может быть несколько сотрудников с одной специализацией. Пользователь выбирает сотрудника в чате как коллегу.",
        questions: &["Какие AI-сотрудники настроены?", "Как добавить сотрудника-аналитика?", "Какая специализация у сотрудника?", "К какому подключению привязан сотрудник?"],
        related: &["a038_llm_connection", "a018_llm_chat", "a019_llm_artifact"],
        tags: &["llm"],
        llm_visible: true,
    },
    access: Some(&ACCESS_META),
};

/// Field metadata array
pub const FIELDS: &[FieldMetadata] = &[
    FieldMetadata {
        name: "id",
        rust_type: "LlmAgentId",
        field_type: FieldType::Primitive,
        source: FieldSource::Base,
        ui: FieldUiMetadata {
            label: "ID",
            label_en: Some("ID"),
            placeholder: None,
            hint: None,
            visible_in_list: false,
            visible_in_form: false,
            widget: None,
            column_width: None,
        },
        validation: ValidationRules {
            required: true,
            min: None,
            max: None,
            min_length: None,
            max_length: None,
            pattern: None,
            custom_error: None,
        },
        ai_hint: None,
        physical: true,
        nested_fields: None,
        ref_aggregate: None,
        enum_values: None,
    },
    FieldMetadata {
        name: "code",
        rust_type: "String",
        field_type: FieldType::Primitive,
        source: FieldSource::Base,
        ui: FieldUiMetadata {
            label: "Код",
            label_en: Some("Code"),
            placeholder: Some("GPT4O-MAIN"),
            hint: Some("Уникальный код агента"),
            visible_in_list: true,
            visible_in_form: true,
            widget: None,
            column_width: Some(150),
        },
        validation: ValidationRules {
            required: true,
            min: None,
            max: None,
            min_length: None,
            max_length: Some(50),
            pattern: None,
            custom_error: None,
        },
        ai_hint: None,
        physical: true,
        nested_fields: None,
        ref_aggregate: None,
        enum_values: None,
    },
    FieldMetadata {
        name: "description",
        rust_type: "String",
        field_type: FieldType::Primitive,
        source: FieldSource::Base,
        ui: FieldUiMetadata {
            label: "Имя сотрудника",
            label_en: Some("Employee Name"),
            placeholder: Some("Анна — аналитик продаж"),
            hint: Some("Имя виртуального сотрудника"),
            visible_in_list: true,
            visible_in_form: true,
            widget: None,
            column_width: Some(250),
        },
        validation: ValidationRules {
            required: true,
            min: None,
            max: None,
            min_length: Some(3),
            max_length: Some(255),
            pattern: None,
            custom_error: None,
        },
        ai_hint: None,
        physical: true,
        nested_fields: None,
        ref_aggregate: None,
        enum_values: None,
    },
    FieldMetadata {
        name: "comment",
        rust_type: "String",
        field_type: FieldType::Primitive,
        source: FieldSource::Base,
        ui: FieldUiMetadata {
            label: "Комментарий",
            label_en: Some("Comment"),
            placeholder: Some("Используется для анализа продаж"),
            hint: Some("Произвольный комментарий"),
            visible_in_list: false,
            visible_in_form: true,
            widget: Some("textarea"),
            column_width: None,
        },
        validation: ValidationRules {
            required: false,
            min: None,
            max: None,
            min_length: None,
            max_length: Some(1000),
            pattern: None,
            custom_error: None,
        },
        ai_hint: None,
        physical: true,
        nested_fields: None,
        ref_aggregate: None,
        enum_values: None,
    },
    FieldMetadata {
        name: "provider_type",
        rust_type: "String",
        field_type: FieldType::Primitive,
        source: FieldSource::Specific,
        ui: FieldUiMetadata {
            label: "Провайдер",
            label_en: Some("Provider"),
            placeholder: None,
            hint: Some("Вестигиально: источник истины — подключение a038"),
            visible_in_list: false,
            visible_in_form: false,
            widget: Some("select"),
            column_width: Some(120),
        },
        validation: ValidationRules {
            required: false,
            min: None,
            max: None,
            min_length: None,
            max_length: None,
            pattern: None,
            custom_error: None,
        },
        ai_hint: Some("Вестигиальное поле. Провайдер берётся из связанного подключения a038 (connection_id)."),
        physical: true,
        nested_fields: None,
        ref_aggregate: None,
        enum_values: None,
    },
    FieldMetadata {
        name: "api_endpoint",
        rust_type: "String",
        field_type: FieldType::Primitive,
        source: FieldSource::Specific,
        ui: FieldUiMetadata {
            label: "API Endpoint",
            label_en: Some("API Endpoint"),
            placeholder: Some("https://api.openai.com/v1"),
            hint: Some("Вестигиально: источник истины — подключение a038"),
            visible_in_list: false,
            visible_in_form: false,
            widget: None,
            column_width: Some(300),
        },
        validation: ValidationRules {
            required: false,
            min: None,
            max: None,
            min_length: None,
            max_length: Some(500),
            pattern: None,
            custom_error: None,
        },
        ai_hint: Some("Вестигиальное поле. Endpoint берётся из связанного подключения a038 (connection_id)."),
        physical: true,
        nested_fields: None,
        ref_aggregate: None,
        enum_values: None,
    },
    FieldMetadata {
        name: "api_key",
        rust_type: "String",
        field_type: FieldType::Primitive,
        source: FieldSource::Specific,
        ui: FieldUiMetadata {
            label: "API Ключ",
            label_en: Some("API Key"),
            placeholder: Some("sk-..."),
            hint: Some("Вестигиально: источник истины — подключение a038"),
            visible_in_list: false,
            visible_in_form: false,
            widget: Some("password"),
            column_width: None,
        },
        validation: ValidationRules {
            required: false,
            min: None,
            max: None,
            min_length: None,
            max_length: Some(500),
            pattern: None,
            custom_error: None,
        },
        ai_hint: Some("Вестигиальное поле. Ключ берётся из связанного подключения a038 (connection_id)."),
        physical: true,
        nested_fields: None,
        ref_aggregate: None,
        enum_values: None,
    },
    FieldMetadata {
        name: "model_name",
        rust_type: "String",
        field_type: FieldType::Primitive,
        source: FieldSource::Specific,
        ui: FieldUiMetadata {
            label: "Модель (закреплённая)",
            label_en: Some("Pinned Model"),
            placeholder: Some("пусто → дефолт подключения"),
            hint: Some("Опционально: закрепить модель из allowed_models подключения; пусто → дефолт подключения"),
            visible_in_list: true,
            visible_in_form: true,
            widget: None,
            column_width: Some(150),
        },
        validation: ValidationRules {
            required: false,
            min: None,
            max: None,
            min_length: None,
            max_length: Some(100),
            pattern: None,
            custom_error: None,
        },
        ai_hint: Some("Опциональная закреплённая модель сотрудника. Должна входить в allowed_models связанного подключения. Пусто → используется дефолтная модель подключения."),
        physical: true,
        nested_fields: None,
        ref_aggregate: None,
        enum_values: None,
    },
    FieldMetadata {
        name: "available_models",
        rust_type: "String",
        field_type: FieldType::Primitive,
        source: FieldSource::Specific,
        ui: FieldUiMetadata {
            label: "Доступные модели",
            label_en: Some("Available Models"),
            placeholder: None,
            hint: Some("JSON список моделей из API"),
            visible_in_list: false,
            visible_in_form: false,
            widget: Some("textarea"),
            column_width: None,
        },
        validation: ValidationRules {
            required: false,
            min: None,
            max: None,
            min_length: None,
            max_length: None,
            pattern: None,
            custom_error: None,
        },
        ai_hint: Some("JSON массив объектов с полями: id, created, owned_by. Загружается из /v1/models API провайдера."),
        physical: true,
        nested_fields: None,
        ref_aggregate: None,
        enum_values: None,
    },
    FieldMetadata {
        name: "temperature",
        rust_type: "f64",
        field_type: FieldType::Primitive,
        source: FieldSource::Specific,
        ui: FieldUiMetadata {
            label: "Temperature",
            label_en: Some("Temperature"),
            placeholder: Some("0.7"),
            hint: Some("Вестигиально: источник истины — подключение a038"),
            visible_in_list: false,
            visible_in_form: false,
            widget: None,
            column_width: None,
        },
        validation: ValidationRules {
            required: false,
            min: Some(0.0),
            max: Some(2.0),
            min_length: None,
            max_length: None,
            pattern: None,
            custom_error: None,
        },
        ai_hint: Some("Вестигиальное поле. Temperature берётся из связанного подключения a038 (connection_id)."),
        physical: true,
        nested_fields: None,
        ref_aggregate: None,
        enum_values: None,
    },
    FieldMetadata {
        name: "max_tokens",
        rust_type: "i32",
        field_type: FieldType::Primitive,
        source: FieldSource::Specific,
        ui: FieldUiMetadata {
            label: "Max Tokens",
            label_en: Some("Max Tokens"),
            placeholder: Some("4096"),
            hint: Some("Вестигиально: источник истины — подключение a038"),
            visible_in_list: false,
            visible_in_form: false,
            widget: None,
            column_width: None,
        },
        validation: ValidationRules {
            required: false,
            min: Some(256.0),
            max: Some(128000.0),
            min_length: None,
            max_length: None,
            pattern: None,
            custom_error: None,
        },
        ai_hint: Some("Вестигиальное поле. Max tokens берётся из связанного подключения a038 (connection_id)."),
        physical: true,
        nested_fields: None,
        ref_aggregate: None,
        enum_values: None,
    },
    FieldMetadata {
        name: "system_prompt",
        rust_type: "String",
        field_type: FieldType::Primitive,
        source: FieldSource::Specific,
        ui: FieldUiMetadata {
            label: "Должностные обязанности",
            label_en: Some("Job Duties"),
            placeholder: Some("Ты — аналитик продаж. Отвечаешь за..."),
            hint: Some("Промпт: роль, зона ответственности, поведение сотрудника"),
            visible_in_list: false,
            visible_in_form: true,
            widget: Some("textarea"),
            column_width: None,
        },
        validation: ValidationRules {
            required: false,
            min: None,
            max: None,
            min_length: None,
            max_length: Some(5000),
            pattern: None,
            custom_error: None,
        },
        ai_hint: Some("Определяет роль и поведение сотрудника. Если пусто — используется role-agnostic core-промпт из skills."),
        physical: true,
        nested_fields: None,
        ref_aggregate: None,
        enum_values: None,
    },
    FieldMetadata {
        name: "agent_type",
        rust_type: "AgentType",
        field_type: FieldType::Primitive,
        source: FieldSource::Specific,
        ui: FieldUiMetadata {
            label: "Специализация",
            label_en: Some("Specialization"),
            placeholder: None,
            hint: Some("Роль/персона — определяет набор навыков и инструментов"),
            visible_in_list: true,
            visible_in_form: true,
            widget: Some("select"),
            column_width: Some(160),
        },
        validation: ValidationRules {
            required: false,
            min: None,
            max: None,
            min_length: None,
            max_length: None,
            pattern: None,
            custom_error: None,
        },
        ai_hint: Some("Специализация задаёт доступные навыки (skills) и default-навык. Может быть несколько сотрудников с одной специализацией. tester — обкаточная роль для локальной модели с урезанной матрицей навыков."),
        physical: true,
        nested_fields: None,
        ref_aggregate: None,
        enum_values: Some(&["business_analyst", "sales_analyst", "marketer", "financier", "system_admin", "kb_admin", "plugin_admin", "coordinator_admin", "tester"]),
    },
    FieldMetadata {
        name: "connection_id",
        rust_type: "String",
        field_type: FieldType::Primitive,
        source: FieldSource::Specific,
        ui: FieldUiMetadata {
            label: "Подключение",
            label_en: Some("Connection"),
            placeholder: None,
            hint: Some("Техническое подключение a038, через которое работает сотрудник"),
            visible_in_list: false,
            visible_in_form: true,
            widget: Some("select"),
            column_width: None,
        },
        validation: ValidationRules {
            required: true,
            min: None,
            max: None,
            min_length: None,
            max_length: None,
            pattern: None,
            custom_error: None,
        },
        ai_hint: Some("UUID подключения a038. Из него сотрудник берёт провайдера, креды и тюнинг."),
        physical: true,
        nested_fields: None,
        ref_aggregate: Some("a038_llm_connection"),
        enum_values: None,
    },
    FieldMetadata {
        name: "avatar",
        rust_type: "String",
        field_type: FieldType::Primitive,
        source: FieldSource::Specific,
        ui: FieldUiMetadata {
            label: "Аватар",
            label_en: Some("Avatar"),
            placeholder: Some("🧑‍💼"),
            hint: Some("Эмодзи, инициалы или URL"),
            visible_in_list: true,
            visible_in_form: true,
            widget: None,
            column_width: Some(80),
        },
        validation: ValidationRules {
            required: false,
            min: None,
            max: None,
            min_length: None,
            max_length: Some(500),
            pattern: None,
            custom_error: None,
        },
        ai_hint: None,
        physical: true,
        nested_fields: None,
        ref_aggregate: None,
        enum_values: None,
    },
    FieldMetadata {
        name: "email",
        rust_type: "String",
        field_type: FieldType::Primitive,
        source: FieldSource::Specific,
        ui: FieldUiMetadata {
            label: "Почта",
            label_en: Some("Email"),
            placeholder: Some("anna@ai.local"),
            hint: Some("Внутренний адрес сотрудника (задел для взаимодействия агентов)"),
            visible_in_list: false,
            visible_in_form: true,
            widget: None,
            column_width: Some(200),
        },
        validation: ValidationRules {
            required: false,
            min: None,
            max: None,
            min_length: None,
            max_length: Some(255),
            pattern: None,
            custom_error: None,
        },
        ai_hint: None,
        physical: true,
        nested_fields: None,
        ref_aggregate: None,
        enum_values: None,
    },
    FieldMetadata {
        name: "schedule_cron",
        rust_type: "String",
        field_type: FieldType::Primitive,
        source: FieldSource::Specific,
        ui: FieldUiMetadata {
            label: "Расписание (cron)",
            label_en: Some("Schedule (cron)"),
            placeholder: Some("0 */2 * * * *"),
            hint: Some("Cron пробуждения сотрудника (задел; исполнитель — отдельной фазой)"),
            visible_in_list: false,
            visible_in_form: true,
            widget: None,
            column_width: Some(150),
        },
        validation: ValidationRules {
            required: false,
            min: None,
            max: None,
            min_length: None,
            max_length: Some(100),
            pattern: None,
            custom_error: None,
        },
        ai_hint: None,
        physical: true,
        nested_fields: None,
        ref_aggregate: None,
        enum_values: None,
    },
    FieldMetadata {
        name: "is_active",
        rust_type: "bool",
        field_type: FieldType::Primitive,
        source: FieldSource::Specific,
        ui: FieldUiMetadata {
            label: "Активен",
            label_en: Some("Active"),
            placeholder: None,
            hint: Some("Нанят / в отпуске"),
            visible_in_list: true,
            visible_in_form: true,
            widget: Some("checkbox"),
            column_width: Some(90),
        },
        validation: ValidationRules {
            required: false,
            min: None,
            max: None,
            min_length: None,
            max_length: None,
            pattern: None,
            custom_error: None,
        },
        ai_hint: None,
        physical: true,
        nested_fields: None,
        ref_aggregate: None,
        enum_values: None,
    },
    FieldMetadata {
        name: "is_primary",
        rust_type: "bool",
        field_type: FieldType::Primitive,
        source: FieldSource::Specific,
        ui: FieldUiMetadata {
            label: "Основной",
            label_en: Some("Primary"),
            placeholder: None,
            hint: Some("Использовать по умолчанию в чате"),
            visible_in_list: true,
            visible_in_form: true,
            widget: Some("checkbox"),
            column_width: Some(100),
        },
        validation: ValidationRules {
            required: false,
            min: None,
            max: None,
            min_length: None,
            max_length: None,
            pattern: None,
            custom_error: None,
        },
        ai_hint: Some("Только один сотрудник может быть основным (дефолт в чате). При установке флага снимается с других."),
        physical: true,
        nested_fields: None,
        ref_aggregate: None,
        enum_values: None,
    },
];
