// ============================================================================
// AUTO-GENERATED FROM metadata.json - DO NOT EDIT MANUALLY
// ============================================================================

#![cfg_attr(rustfmt, rustfmt::skip)]

#![allow(dead_code)]

use crate::shared::metadata::{
    EntityMetadataInfo, EntityType, EntityUiMetadata, EntityAiMetadata,
    FieldMetadata, FieldType, FieldSource, FieldUiMetadata, ValidationRules
};
use crate::shared::access::{EntityAccessMeta, ScopeOperation, AccessMode};

/// Access scope metadata for this entity
pub const ACCESS_META: EntityAccessMeta = EntityAccessMeta {
    scope_id: "a037_wb_product_snapshot",
    operations: &[
    ScopeOperation { id: "list", required_mode: AccessMode::Read },
    ScopeOperation { id: "get", required_mode: AccessMode::Read },
    ScopeOperation { id: "upsert", required_mode: AccessMode::All },
    ScopeOperation { id: "delete", required_mode: AccessMode::All }
    ],
};

/// Entity metadata for WbProductSnapshot aggregate
pub const ENTITY_METADATA: EntityMetadataInfo = EntityMetadataInfo {
    schema_version: "1.0",
    entity_type: EntityType::Aggregate,
    entity_name: "WbProductSnapshot",
    entity_index: "a037",
    collection_name: "wb_product_snapshot",
    table_name: Some("a037_wb_product_snapshot"),
    ui: EntityUiMetadata {
        element_name: "Данные по товарам WB",
        element_name_en: Some("WB Product Snapshot"),
        list_name: "Данные по товарам WB по дням",
        list_name_en: Some("WB Product Daily Snapshots"),
        icon: Some("package"),
    },
    ai: EntityAiMetadata {
        description: "Ежедневные снимки состояния товаров Wildberries в разрезе номенклатуры: остатки на складах WB и продавца, сумма остатков, рейтинг карточки и оценка покупателей на дату снятия. Данные снимаются только вперёд (WB отдаёт остатки/рейтинги лишь как текущее состояние); один документ — один кабинет WB и одна дата. Используется для анализа динамики остатков и рейтингов по дням.",
        questions: &["Как менялся остаток товара WB по дням?", "Какие товары уходят в out-of-stock?", "Как менялся рейтинг карточки товара?", "Сколько всего остатков на складах WB по кабинету?", "Динамика оценок покупателей по товару?"],
        related: &["a006_connection_mp", "a002_organization", "a007_marketplace_product", "a036_wb_sales_funnel_daily"],
        tags: &["wb", "analytics", "stocks"],
        llm_visible: true,
    },
    access: Some(&ACCESS_META),
};

/// Field metadata array
pub const FIELDS: &[FieldMetadata] = &[
    FieldMetadata {
        name: "id",
        rust_type: "WbProductSnapshotId",
        field_type: FieldType::Primitive,
        source: FieldSource::Base,
        ui: FieldUiMetadata {
            label: "ID",
            label_en: None,
            placeholder: None,
            hint: None,
            visible_in_list: false,
            visible_in_form: false,
            widget: None,
            column_width: None,
        },
        validation: ValidationRules {
            required: true,
            min: None,
            max: None,
            min_length: None,
            max_length: None,
            pattern: None,
            custom_error: None,
        },
        ai_hint: None,
        physical: true,
        nested_fields: None,
        ref_aggregate: None,
        enum_values: None,
    },
    FieldMetadata {
        name: "code",
        rust_type: "String",
        field_type: FieldType::Primitive,
        source: FieldSource::Base,
        ui: FieldUiMetadata {
            label: "Код",
            label_en: None,
            placeholder: None,
            hint: None,
            visible_in_list: true,
            visible_in_form: false,
            widget: None,
            column_width: Some(160),
        },
        validation: ValidationRules {
            required: true,
            min: None,
            max: None,
            min_length: None,
            max_length: None,
            pattern: None,
            custom_error: None,
        },
        ai_hint: Some("Внутренний код документа снимка товаров WB."),
        physical: true,
        nested_fields: None,
        ref_aggregate: None,
        enum_values: None,
    },
    FieldMetadata {
        name: "description",
        rust_type: "String",
        field_type: FieldType::Primitive,
        source: FieldSource::Base,
        ui: FieldUiMetadata {
            label: "Описание",
            label_en: None,
            placeholder: None,
            hint: None,
            visible_in_list: true,
            visible_in_form: false,
            widget: None,
            column_width: Some(260),
        },
        validation: ValidationRules {
            required: true,
            min: None,
            max: None,
            min_length: None,
            max_length: None,
            pattern: None,
            custom_error: None,
        },
        ai_hint: Some("Человекочитаемое описание документа: дата снимка."),
        physical: true,
        nested_fields: None,
        ref_aggregate: None,
        enum_values: None,
    },
    FieldMetadata {
        name: "document_no",
        rust_type: "String",
        field_type: FieldType::Primitive,
        source: FieldSource::Specific,
        ui: FieldUiMetadata {
            label: "Номер документа",
            label_en: None,
            placeholder: None,
            hint: None,
            visible_in_list: false,
            visible_in_form: false,
            widget: None,
            column_width: Some(160),
        },
        validation: ValidationRules {
            required: true,
            min: None,
            max: None,
            min_length: None,
            max_length: None,
            pattern: None,
            custom_error: None,
        },
        ai_hint: Some("Технический номер документа снимка."),
        physical: true,
        nested_fields: None,
        ref_aggregate: None,
        enum_values: None,
    },
    FieldMetadata {
        name: "document_date",
        rust_type: "String",
        field_type: FieldType::Primitive,
        source: FieldSource::Specific,
        ui: FieldUiMetadata {
            label: "Дата",
            label_en: None,
            placeholder: None,
            hint: None,
            visible_in_list: true,
            visible_in_form: false,
            widget: Some("date"),
            column_width: Some(120),
        },
        validation: ValidationRules {
            required: true,
            min: None,
            max: None,
            min_length: None,
            max_length: None,
            pattern: None,
            custom_error: None,
        },
        ai_hint: Some("Дата снятия снимка WB. Для периода используй document_date >= 'YYYY-MM-DD' AND document_date < 'YYYY-MM-DD'."),
        physical: true,
        nested_fields: None,
        ref_aggregate: None,
        enum_values: None,
    },
    FieldMetadata {
        name: "connection_id",
        rust_type: "String",
        field_type: FieldType::AggregateRef,
        source: FieldSource::Specific,
        ui: FieldUiMetadata {
            label: "Подключение (магазин WB)",
            label_en: None,
            placeholder: None,
            hint: None,
            visible_in_list: true,
            visible_in_form: false,
            widget: None,
            column_width: Some(220),
        },
        validation: ValidationRules {
            required: true,
            min: None,
            max: None,
            min_length: None,
            max_length: None,
            pattern: None,
            custom_error: None,
        },
        ai_hint: Some("UUID подключения магазина WB из a006_connection_mp. JOIN a006_connection_mp ON a037_wb_product_snapshot.connection_id = a006_connection_mp.id."),
        physical: true,
        nested_fields: None,
        ref_aggregate: Some("a006_connection_mp"),
        enum_values: None,
    },
    FieldMetadata {
        name: "organization_id",
        rust_type: "String",
        field_type: FieldType::AggregateRef,
        source: FieldSource::Specific,
        ui: FieldUiMetadata {
            label: "Организация",
            label_en: None,
            placeholder: None,
            hint: None,
            visible_in_list: false,
            visible_in_form: false,
            widget: None,
            column_width: Some(220),
        },
        validation: ValidationRules {
            required: true,
            min: None,
            max: None,
            min_length: None,
            max_length: None,
            pattern: None,
            custom_error: None,
        },
        ai_hint: Some("UUID организации из a002_organization."),
        physical: true,
        nested_fields: None,
        ref_aggregate: Some("a002_organization"),
        enum_values: None,
    },
    FieldMetadata {
        name: "marketplace_id",
        rust_type: "String",
        field_type: FieldType::AggregateRef,
        source: FieldSource::Specific,
        ui: FieldUiMetadata {
            label: "Маркетплейс",
            label_en: None,
            placeholder: None,
            hint: None,
            visible_in_list: false,
            visible_in_form: false,
            widget: None,
            column_width: Some(180),
        },
        validation: ValidationRules {
            required: true,
            min: None,
            max: None,
            min_length: None,
            max_length: None,
            pattern: None,
            custom_error: None,
        },
        ai_hint: Some("UUID маркетплейса из a005_marketplace. Для WB обычно marketplace code = 'mp-wb'."),
        physical: true,
        nested_fields: None,
        ref_aggregate: Some("a005_marketplace"),
        enum_values: None,
    },
    FieldMetadata {
        name: "lines_count",
        rust_type: "i32",
        field_type: FieldType::Primitive,
        source: FieldSource::Specific,
        ui: FieldUiMetadata {
            label: "Позиций",
            label_en: None,
            placeholder: None,
            hint: None,
            visible_in_list: true,
            visible_in_form: false,
            widget: None,
            column_width: Some(90),
        },
        validation: ValidationRules {
            required: true,
            min: None,
            max: None,
            min_length: None,
            max_length: None,
            pattern: None,
            custom_error: None,
        },
        ai_hint: Some("Количество товарных строк в JSON детализации lines_json."),
        physical: true,
        nested_fields: None,
        ref_aggregate: None,
        enum_values: None,
    },
    FieldMetadata {
        name: "total_stock_wb",
        rust_type: "i64",
        field_type: FieldType::Primitive,
        source: FieldSource::Specific,
        ui: FieldUiMetadata {
            label: "Остаток WB",
            label_en: None,
            placeholder: None,
            hint: None,
            visible_in_list: true,
            visible_in_form: false,
            widget: None,
            column_width: Some(110),
        },
        validation: ValidationRules {
            required: true,
            min: None,
            max: None,
            min_length: None,
            max_length: None,
            pattern: None,
            custom_error: None,
        },
        ai_hint: Some("Суммарный остаток на складах WB на дату снимка."),
        physical: true,
        nested_fields: None,
        ref_aggregate: None,
        enum_values: None,
    },
    FieldMetadata {
        name: "total_stock_mp",
        rust_type: "i64",
        field_type: FieldType::Primitive,
        source: FieldSource::Specific,
        ui: FieldUiMetadata {
            label: "Остаток продавца",
            label_en: None,
            placeholder: None,
            hint: None,
            visible_in_list: true,
            visible_in_form: false,
            widget: None,
            column_width: Some(120),
        },
        validation: ValidationRules {
            required: true,
            min: None,
            max: None,
            min_length: None,
            max_length: None,
            pattern: None,
            custom_error: None,
        },
        ai_hint: Some("Суммарный остаток на складах продавца на дату снимка."),
        physical: true,
        nested_fields: None,
        ref_aggregate: None,
        enum_values: None,
    },
    FieldMetadata {
        name: "total_balance_sum",
        rust_type: "f64",
        field_type: FieldType::Primitive,
        source: FieldSource::Specific,
        ui: FieldUiMetadata {
            label: "Сумма остатков",
            label_en: None,
            placeholder: None,
            hint: None,
            visible_in_list: true,
            visible_in_form: false,
            widget: Some("number"),
            column_width: Some(130),
        },
        validation: ValidationRules {
            required: true,
            min: None,
            max: None,
            min_length: None,
            max_length: None,
            pattern: None,
            custom_error: None,
        },
        ai_hint: Some("Суммарная стоимость остатков на дату снимка."),
        physical: true,
        nested_fields: None,
        ref_aggregate: None,
        enum_values: None,
    },
    FieldMetadata {
        name: "lines_json",
        rust_type: "String",
        field_type: FieldType::Primitive,
        source: FieldSource::Specific,
        ui: FieldUiMetadata {
            label: "Строки JSON",
            label_en: None,
            placeholder: None,
            hint: None,
            visible_in_list: false,
            visible_in_form: false,
            widget: Some("textarea"),
            column_width: None,
        },
        validation: ValidationRules {
            required: true,
            min: None,
            max: None,
            min_length: None,
            max_length: None,
            pattern: None,
            custom_error: None,
        },
        ai_hint: Some("JSON-массив детализации по товарам (одна запись = один nm_id на дату снимка). Ключи строки: nm_id, title, vendor_code, brand_name, subject, stock_wb, stock_mp, stock_balance_sum, product_rating, feedback_rating. Для анализа В РАЗРЕЗЕ НОМЕНКЛАТУРЫ разворачивай массив через json_each и доставай поля через json_extract(j.value,'$.поле'). Пример (динамика остатка и рейтинга одного товара по дням): SELECT d.document_date, json_extract(j.value,'$.stock_wb') AS stock_wb, json_extract(j.value,'$.product_rating') AS rating FROM a037_wb_product_snapshot d, json_each(d.lines_json) j WHERE json_extract(j.value,'$.nm_id') = 12345678 ORDER BY d.document_date. Для дневных ИТОГОВ по кабинету используй готовые колонки total_stock_wb/total_stock_mp/total_balance_sum — json_each не нужен."),
        physical: true,
        nested_fields: None,
        ref_aggregate: None,
        enum_values: None,
    },
    FieldMetadata {
        name: "fetched_at",
        rust_type: "String",
        field_type: FieldType::Primitive,
        source: FieldSource::Specific,
        ui: FieldUiMetadata {
            label: "Загружено",
            label_en: None,
            placeholder: None,
            hint: None,
            visible_in_list: false,
            visible_in_form: false,
            widget: Some("datetime"),
            column_width: Some(160),
        },
        validation: ValidationRules {
            required: true,
            min: None,
            max: None,
            min_length: None,
            max_length: None,
            pattern: None,
            custom_error: None,
        },
        ai_hint: Some("Дата и время получения данных из WB Analytics API."),
        physical: true,
        nested_fields: None,
        ref_aggregate: None,
        enum_values: None,
    },
    FieldMetadata {
        name: "header_json",
        rust_type: "String",
        field_type: FieldType::Primitive,
        source: FieldSource::Specific,
        ui: FieldUiMetadata {
            label: "Header (JSON)",
            label_en: None,
            placeholder: None,
            hint: None,
            visible_in_list: false,
            visible_in_form: true,
            widget: None,
            column_width: None,
        },
        validation: ValidationRules {
            required: true,
            min: None,
            max: None,
            min_length: None,
            max_length: None,
            pattern: None,
            custom_error: None,
        },
        ai_hint: Some("JSON-поле документа: хранит вложенную структуру целиком. Логические поля документа доступны через json_extract по этой колонке."),
        physical: true,
        nested_fields: None,
        ref_aggregate: None,
        enum_values: None,
    },
    FieldMetadata {
        name: "totals_json",
        rust_type: "String",
        field_type: FieldType::Primitive,
        source: FieldSource::Specific,
        ui: FieldUiMetadata {
            label: "Totals (JSON)",
            label_en: None,
            placeholder: None,
            hint: None,
            visible_in_list: false,
            visible_in_form: true,
            widget: None,
            column_width: None,
        },
        validation: ValidationRules {
            required: true,
            min: None,
            max: None,
            min_length: None,
            max_length: None,
            pattern: None,
            custom_error: None,
        },
        ai_hint: Some("JSON-поле документа: хранит вложенную структуру целиком. Логические поля документа доступны через json_extract по этой колонке."),
        physical: true,
        nested_fields: None,
        ref_aggregate: None,
        enum_values: None,
    },
    FieldMetadata {
        name: "source_meta_json",
        rust_type: "String",
        field_type: FieldType::Primitive,
        source: FieldSource::Specific,
        ui: FieldUiMetadata {
            label: "Source Meta (JSON)",
            label_en: None,
            placeholder: None,
            hint: None,
            visible_in_list: false,
            visible_in_form: true,
            widget: None,
            column_width: None,
        },
        validation: ValidationRules {
            required: true,
            min: None,
            max: None,
            min_length: None,
            max_length: None,
            pattern: None,
            custom_error: None,
        },
        ai_hint: Some("JSON-поле документа: хранит вложенную структуру целиком. Логические поля документа доступны через json_extract по этой колонке."),
        physical: true,
        nested_fields: None,
        ref_aggregate: None,
        enum_values: None,
    },
];
