// ============================================================================
// AUTO-GENERATED FROM metadata.json - DO NOT EDIT MANUALLY
// ============================================================================

#![cfg_attr(rustfmt, rustfmt::skip)]

#![allow(dead_code)]

use crate::shared::metadata::{
    EntityMetadataInfo, EntityType, EntityUiMetadata, EntityAiMetadata,
    FieldMetadata, FieldType, FieldSource, FieldUiMetadata, ValidationRules
};
use crate::shared::access::{EntityAccessMeta, ScopeOperation, AccessMode};

/// Access scope metadata for this entity
pub const ACCESS_META: EntityAccessMeta = EntityAccessMeta {
    scope_id: "a012_wb_sales",
    operations: &[
    ScopeOperation { id: "list", required_mode: AccessMode::Read },
    ScopeOperation { id: "get", required_mode: AccessMode::Read }
    ],
};

/// Entity metadata for WbSales aggregate
pub const ENTITY_METADATA: EntityMetadataInfo = EntityMetadataInfo {
    schema_version: "1.0",
    entity_type: EntityType::Aggregate,
    entity_name: "WbSales",
    entity_index: "a012",
    collection_name: "wb_sales",
    table_name: Some("a012_wb_sales"),
    ui: EntityUiMetadata {
        element_name: "WB Sales",
        element_name_en: Some("WB Sales"),
        list_name: "WB Sales",
        list_name_en: Some("WB Sales"),
        icon: Some("shopping-bag"),
    },
    ai: EntityAiMetadata {
        description: "Продажи и возвраты с Wildberries. Каждая запись — одна транзакция из отчёта WB (sale или return). Содержит финансовые показатели: выручку, комиссию WB, прибыль план/факт. Данные загружаются через WB API. Для расчёта выручки фильтруй event_type = 'Продажа', для возвратов — 'Возврат'. Поле sale_date позволяет строить графики продаж по дням и дням недели.",
        questions: &["Какова выручка WB за период?", "Топ-10 товаров по продажам на WB", "Процент возвратов по артикулу", "Прибыль по магазинам WB", "Сколько продано штук товара X?"],
        related: &["a004_nomenclature", "a006_connection_mp", "a002_organization"],
        tags: &["wb", "sales"],
        llm_visible: true,
    },
    access: Some(&ACCESS_META),
};

/// Field metadata array
pub const FIELDS: &[FieldMetadata] = &[
    FieldMetadata {
        name: "id",
        rust_type: "WbSalesId",
        field_type: FieldType::Primitive,
        source: FieldSource::Base,
        ui: FieldUiMetadata {
            label: "ID",
            label_en: None,
            placeholder: None,
            hint: None,
            visible_in_list: false,
            visible_in_form: false,
            widget: None,
            column_width: None,
        },
        validation: ValidationRules {
            required: true,
            min: None,
            max: None,
            min_length: None,
            max_length: None,
            pattern: None,
            custom_error: None,
        },
        ai_hint: None,
        physical: true,
        nested_fields: None,
        ref_aggregate: None,
        enum_values: None,
    },
    FieldMetadata {
        name: "sale_date",
        rust_type: "DateTime<Utc>",
        field_type: FieldType::Primitive,
        source: FieldSource::Specific,
        ui: FieldUiMetadata {
            label: "Дата продажи",
            label_en: Some("Sale Date"),
            placeholder: None,
            hint: None,
            visible_in_list: true,
            visible_in_form: false,
            widget: Some("datetime"),
            column_width: Some(160),
        },
        validation: ValidationRules {
            required: false,
            min: None,
            max: None,
            min_length: None,
            max_length: None,
            pattern: None,
            custom_error: None,
        },
        ai_hint: Some("Дата и время продажи/возврата. Хранится в формате ISO 8601 (TEXT). Для группировки по дням: date(sale_date). Для фильтра по месяцу: strftime('%Y-%m', sale_date) = '2024-01'."),
        physical: true,
        nested_fields: None,
        ref_aggregate: None,
        enum_values: None,
    },
    FieldMetadata {
        name: "connection_id",
        rust_type: "String",
        field_type: FieldType::AggregateRef,
        source: FieldSource::Specific,
        ui: FieldUiMetadata {
            label: "Подключение (магазин WB)",
            label_en: Some("Connection (WB shop)"),
            placeholder: None,
            hint: None,
            visible_in_list: true,
            visible_in_form: false,
            widget: None,
            column_width: Some(200),
        },
        validation: ValidationRules {
            required: true,
            min: None,
            max: None,
            min_length: None,
            max_length: None,
            pattern: None,
            custom_error: None,
        },
        ai_hint: Some("UUID подключения магазина WB из a006_connection_mp. Для названия магазина: JOIN a006_connection_mp ON a012_wb_sales.connection_id = a006_connection_mp.id."),
        physical: true,
        nested_fields: None,
        ref_aggregate: Some("a006_connection_mp"),
        enum_values: None,
    },
    FieldMetadata {
        name: "organization_id",
        rust_type: "String",
        field_type: FieldType::AggregateRef,
        source: FieldSource::Specific,
        ui: FieldUiMetadata {
            label: "Организация",
            label_en: Some("Organization"),
            placeholder: None,
            hint: None,
            visible_in_list: true,
            visible_in_form: false,
            widget: None,
            column_width: Some(200),
        },
        validation: ValidationRules {
            required: true,
            min: None,
            max: None,
            min_length: None,
            max_length: None,
            pattern: None,
            custom_error: None,
        },
        ai_hint: Some("UUID организации из a002_organization."),
        physical: true,
        nested_fields: None,
        ref_aggregate: Some("a002_organization"),
        enum_values: None,
    },
    FieldMetadata {
        name: "supplier_article",
        rust_type: "String",
        field_type: FieldType::Primitive,
        source: FieldSource::Specific,
        ui: FieldUiMetadata {
            label: "Артикул продавца",
            label_en: Some("Supplier Article"),
            placeholder: None,
            hint: None,
            visible_in_list: true,
            visible_in_form: false,
            widget: None,
            column_width: Some(160),
        },
        validation: ValidationRules {
            required: false,
            min: None,
            max: None,
            min_length: None,
            max_length: None,
            pattern: None,
            custom_error: None,
        },
        ai_hint: Some("Артикул продавца на WB. Соответствует полю article в a004_nomenclature."),
        physical: true,
        nested_fields: None,
        ref_aggregate: None,
        enum_values: None,
    },
    FieldMetadata {
        name: "nm_id",
        rust_type: "i64",
        field_type: FieldType::Primitive,
        source: FieldSource::Specific,
        ui: FieldUiMetadata {
            label: "nmId WB",
            label_en: Some("WB nmId"),
            placeholder: None,
            hint: None,
            visible_in_list: true,
            visible_in_form: false,
            widget: None,
            column_width: Some(120),
        },
        validation: ValidationRules {
            required: false,
            min: None,
            max: None,
            min_length: None,
            max_length: None,
            pattern: None,
            custom_error: None,
        },
        ai_hint: Some("Числовой ID номенклатуры в системе Wildberries (nmId). Соответствует nm_id в таблице p908_wb_goods_prices."),
        physical: true,
        nested_fields: None,
        ref_aggregate: None,
        enum_values: None,
    },
    FieldMetadata {
        name: "product_name",
        rust_type: "String",
        field_type: FieldType::Primitive,
        source: FieldSource::Specific,
        ui: FieldUiMetadata {
            label: "Название товара",
            label_en: Some("Product Name"),
            placeholder: None,
            hint: None,
            visible_in_list: true,
            visible_in_form: false,
            widget: None,
            column_width: Some(300),
        },
        validation: ValidationRules {
            required: false,
            min: None,
            max: None,
            min_length: None,
            max_length: None,
            pattern: None,
            custom_error: None,
        },
        ai_hint: Some("Название товара из WB API (денормализованное поле)."),
        physical: true,
        nested_fields: None,
        ref_aggregate: None,
        enum_values: None,
    },
    FieldMetadata {
        name: "qty",
        rust_type: "f64",
        field_type: FieldType::Primitive,
        source: FieldSource::Specific,
        ui: FieldUiMetadata {
            label: "Количество",
            label_en: Some("Quantity"),
            placeholder: None,
            hint: None,
            visible_in_list: true,
            visible_in_form: false,
            widget: None,
            column_width: Some(100),
        },
        validation: ValidationRules {
            required: false,
            min: None,
            max: None,
            min_length: None,
            max_length: None,
            pattern: None,
            custom_error: None,
        },
        ai_hint: Some("Количество проданных единиц. Обычно 1 для продаж, -1 для возвратов. Для суммы продаж: SUM(qty) WHERE event_type='Продажа'."),
        physical: true,
        nested_fields: None,
        ref_aggregate: None,
        enum_values: None,
    },
    FieldMetadata {
        name: "total_price",
        rust_type: "Option<f64>",
        field_type: FieldType::Primitive,
        source: FieldSource::Specific,
        ui: FieldUiMetadata {
            label: "Цена",
            label_en: Some("Price"),
            placeholder: None,
            hint: None,
            visible_in_list: true,
            visible_in_form: false,
            widget: None,
            column_width: Some(120),
        },
        validation: ValidationRules {
            required: false,
            min: None,
            max: None,
            min_length: None,
            max_length: None,
            pattern: None,
            custom_error: None,
        },
        ai_hint: Some("Полная цена товара до скидок (розничная цена). В рублях."),
        physical: true,
        nested_fields: None,
        ref_aggregate: None,
        enum_values: None,
    },
    FieldMetadata {
        name: "finished_price",
        rust_type: "Option<f64>",
        field_type: FieldType::Primitive,
        source: FieldSource::Specific,
        ui: FieldUiMetadata {
            label: "Итоговая сумма",
            label_en: Some("Finished Price"),
            placeholder: None,
            hint: None,
            visible_in_list: true,
            visible_in_form: false,
            widget: None,
            column_width: Some(140),
        },
        validation: ValidationRules {
            required: false,
            min: None,
            max: None,
            min_length: None,
            max_length: None,
            pattern: None,
            custom_error: None,
        },
        ai_hint: Some("Итоговая сумма к оплате покупателем после всех скидок (finishedPrice из WB API). Основной показатель выручки. Для SUM выручки: SUM(finished_price) WHERE event_type='Продажа'."),
        physical: true,
        nested_fields: None,
        ref_aggregate: None,
        enum_values: None,
    },
    FieldMetadata {
        name: "event_type",
        rust_type: "String",
        field_type: FieldType::Primitive,
        source: FieldSource::Specific,
        ui: FieldUiMetadata {
            label: "Тип события",
            label_en: Some("Event Type"),
            placeholder: None,
            hint: None,
            visible_in_list: true,
            visible_in_form: false,
            widget: None,
            column_width: Some(120),
        },
        validation: ValidationRules {
            required: false,
            min: None,
            max: None,
            min_length: None,
            max_length: None,
            pattern: None,
            custom_error: None,
        },
        ai_hint: Some("Тип операции: 'Продажа' или 'Возврат'. Всегда фильтруй по этому полю при расчёте выручки или прибыли."),
        physical: true,
        nested_fields: None,
        ref_aggregate: None,
        enum_values: None,
    },
    FieldMetadata {
        name: "profit_fact",
        rust_type: "Option<f64>",
        field_type: FieldType::Primitive,
        source: FieldSource::Specific,
        ui: FieldUiMetadata {
            label: "Прибыль (факт)",
            label_en: Some("Profit (Fact)"),
            placeholder: None,
            hint: None,
            visible_in_list: true,
            visible_in_form: false,
            widget: None,
            column_width: Some(140),
        },
        validation: ValidationRules {
            required: false,
            min: None,
            max: None,
            min_length: None,
            max_length: None,
            pattern: None,
            custom_error: None,
        },
        ai_hint: Some("Фактическая прибыль = выручка - себестоимость - комиссия WB - эквайринг. NULL если нет данных о себестоимости. Для анализа рентабельности: SUM(profit_fact) WHERE event_type='Продажа' AND profit_fact IS NOT NULL."),
        physical: true,
        nested_fields: None,
        ref_aggregate: None,
        enum_values: None,
    },
    FieldMetadata {
        name: "commission_fact",
        rust_type: "Option<f64>",
        field_type: FieldType::Primitive,
        source: FieldSource::Specific,
        ui: FieldUiMetadata {
            label: "Комиссия WB (факт)",
            label_en: Some("Commission (Fact)"),
            placeholder: None,
            hint: None,
            visible_in_list: false,
            visible_in_form: false,
            widget: None,
            column_width: Some(150),
        },
        validation: ValidationRules {
            required: false,
            min: None,
            max: None,
            min_length: None,
            max_length: None,
            pattern: None,
            custom_error: None,
        },
        ai_hint: Some("Фактический размер комиссии WB в рублях."),
        physical: true,
        nested_fields: None,
        ref_aggregate: None,
        enum_values: None,
    },
    FieldMetadata {
        name: "dealer_price_ut",
        rust_type: "Option<f64>",
        field_type: FieldType::Primitive,
        source: FieldSource::Specific,
        ui: FieldUiMetadata {
            label: "Дилерская цена 1С",
            label_en: Some("Dealer Price (1C)"),
            placeholder: None,
            hint: None,
            visible_in_list: false,
            visible_in_form: false,
            widget: None,
            column_width: Some(150),
        },
        validation: ValidationRules {
            required: false,
            min: None,
            max: None,
            min_length: None,
            max_length: None,
            pattern: None,
            custom_error: None,
        },
        ai_hint: Some("Закупочная/дилерская цена товара из 1С:УТ (себестоимость). Заполняется при проведении документа."),
        physical: true,
        nested_fields: None,
        ref_aggregate: None,
        enum_values: None,
    },
    FieldMetadata {
        name: "nomenclature_ref",
        rust_type: "Option<String>",
        field_type: FieldType::AggregateRef,
        source: FieldSource::Specific,
        ui: FieldUiMetadata {
            label: "Номенклатура 1С",
            label_en: Some("1C Nomenclature"),
            placeholder: None,
            hint: None,
            visible_in_list: false,
            visible_in_form: false,
            widget: None,
            column_width: Some(200),
        },
        validation: ValidationRules {
            required: false,
            min: None,
            max: None,
            min_length: None,
            max_length: None,
            pattern: None,
            custom_error: None,
        },
        ai_hint: Some("UUID номенклатуры из a004_nomenclature. Устанавливается при сопоставлении товаров. JOIN: a012_wb_sales.nomenclature_ref = a004_nomenclature.id."),
        physical: true,
        nested_fields: None,
        ref_aggregate: Some("a004_nomenclature"),
        enum_values: None,
    },
    FieldMetadata {
        name: "sale_id",
        rust_type: "Option<String>",
        field_type: FieldType::Primitive,
        source: FieldSource::Specific,
        ui: FieldUiMetadata {
            label: "ID продажи WB",
            label_en: Some("WB Sale ID"),
            placeholder: None,
            hint: None,
            visible_in_list: false,
            visible_in_form: false,
            widget: None,
            column_width: Some(160),
        },
        validation: ValidationRules {
            required: false,
            min: None,
            max: None,
            min_length: None,
            max_length: None,
            pattern: None,
            custom_error: None,
        },
        ai_hint: Some("Уникальный ID продажи в системе WB (saleID). Используется для дедупликации."),
        physical: true,
        nested_fields: None,
        ref_aggregate: None,
        enum_values: None,
    },
    FieldMetadata {
        name: "header_json",
        rust_type: "String",
        field_type: FieldType::Primitive,
        source: FieldSource::Specific,
        ui: FieldUiMetadata {
            label: "Header (JSON)",
            label_en: None,
            placeholder: None,
            hint: None,
            visible_in_list: false,
            visible_in_form: true,
            widget: None,
            column_width: None,
        },
        validation: ValidationRules {
            required: true,
            min: None,
            max: None,
            min_length: None,
            max_length: None,
            pattern: None,
            custom_error: None,
        },
        ai_hint: Some("JSON-поле документа: хранит вложенную структуру целиком. Логические поля документа доступны через json_extract по этой колонке."),
        physical: true,
        nested_fields: None,
        ref_aggregate: None,
        enum_values: None,
    },
    FieldMetadata {
        name: "line_json",
        rust_type: "String",
        field_type: FieldType::Primitive,
        source: FieldSource::Specific,
        ui: FieldUiMetadata {
            label: "Line (JSON)",
            label_en: None,
            placeholder: None,
            hint: None,
            visible_in_list: false,
            visible_in_form: true,
            widget: None,
            column_width: None,
        },
        validation: ValidationRules {
            required: true,
            min: None,
            max: None,
            min_length: None,
            max_length: None,
            pattern: None,
            custom_error: None,
        },
        ai_hint: Some("JSON-поле документа: хранит вложенную структуру целиком. Логические поля документа доступны через json_extract по этой колонке."),
        physical: true,
        nested_fields: None,
        ref_aggregate: None,
        enum_values: None,
    },
    FieldMetadata {
        name: "state_json",
        rust_type: "String",
        field_type: FieldType::Primitive,
        source: FieldSource::Specific,
        ui: FieldUiMetadata {
            label: "State (JSON)",
            label_en: None,
            placeholder: None,
            hint: None,
            visible_in_list: false,
            visible_in_form: true,
            widget: None,
            column_width: None,
        },
        validation: ValidationRules {
            required: true,
            min: None,
            max: None,
            min_length: None,
            max_length: None,
            pattern: None,
            custom_error: None,
        },
        ai_hint: Some("JSON-поле документа: хранит вложенную структуру целиком. Логические поля документа доступны через json_extract по этой колонке."),
        physical: true,
        nested_fields: None,
        ref_aggregate: None,
        enum_values: None,
    },
    FieldMetadata {
        name: "warehouse_json",
        rust_type: "Option<String>",
        field_type: FieldType::Primitive,
        source: FieldSource::Specific,
        ui: FieldUiMetadata {
            label: "Warehouse (JSON)",
            label_en: None,
            placeholder: None,
            hint: None,
            visible_in_list: false,
            visible_in_form: true,
            widget: None,
            column_width: None,
        },
        validation: ValidationRules {
            required: false,
            min: None,
            max: None,
            min_length: None,
            max_length: None,
            pattern: None,
            custom_error: None,
        },
        ai_hint: Some("JSON-поле документа: хранит вложенную структуру целиком. Логические поля документа доступны через json_extract по этой колонке."),
        physical: true,
        nested_fields: None,
        ref_aggregate: None,
        enum_values: None,
    },
    FieldMetadata {
        name: "source_meta_json",
        rust_type: "String",
        field_type: FieldType::Primitive,
        source: FieldSource::Specific,
        ui: FieldUiMetadata {
            label: "Source Meta (JSON)",
            label_en: None,
            placeholder: None,
            hint: None,
            visible_in_list: false,
            visible_in_form: true,
            widget: None,
            column_width: None,
        },
        validation: ValidationRules {
            required: true,
            min: None,
            max: None,
            min_length: None,
            max_length: None,
            pattern: None,
            custom_error: None,
        },
        ai_hint: Some("JSON-поле документа: хранит вложенную структуру целиком. Логические поля документа доступны через json_extract по этой колонке."),
        physical: true,
        nested_fields: None,
        ref_aggregate: None,
        enum_values: None,
    },
];
